# Generated by Django 4.2.24 on 2025-09-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
        ('nation', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_centers', to='nation.nation')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_centers', to='game.phase')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_centers', to='province.province')),
            ],
        ),
    ]
