# Generated by Django 4.2.24 on 2025-09-24 14:25

from django.db import migrations


def add_classical_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    # Get the classical variant and template phase
    classical_variant = Variant.objects.get(id="classical")
    template_phase = Phase.objects.get(game=None, variant=classical_variant, status="template")

    # Classical supply centers data
    supply_centers_data = [
        {"nation": "England", "province": "edi"},
        {"nation": "England", "province": "lvp"},
        {"nation": "England", "province": "lon"},
        {"nation": "France", "province": "bre"},
        {"nation": "France", "province": "par"},
        {"nation": "France", "province": "mar"},
        {"nation": "Germany", "province": "kie"},
        {"nation": "Germany", "province": "ber"},
        {"nation": "Germany", "province": "mun"},
        {"nation": "Italy", "province": "ven"},
        {"nation": "Italy", "province": "rom"},
        {"nation": "Italy", "province": "nap"},
        {"nation": "Austria", "province": "tri"},
        {"nation": "Austria", "province": "vie"},
        {"nation": "Austria", "province": "bud"},
        {"nation": "Turkey", "province": "con"},
        {"nation": "Turkey", "province": "ank"},
        {"nation": "Turkey", "province": "smy"},
        {"nation": "Russia", "province": "sev"},
        {"nation": "Russia", "province": "mos"},
        {"nation": "Russia", "province": "stp"},
        {"nation": "Russia", "province": "war"},
    ]

    # Create supply centers
    for sc_data in supply_centers_data:
        # Get the nation and province objects
        nation = Nation.objects.get(name=sc_data["nation"], variant=classical_variant)
        province = Province.objects.get(province_id=sc_data["province"], variant=classical_variant)

        SupplyCenter.objects.create(
            phase=template_phase,
            nation=nation,
            province=province,
        )


def remove_classical_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    classical_variant = Variant.objects.get(id="classical")
    template_phase = Phase.objects.get(game=None, variant=classical_variant, status="template")
    SupplyCenter.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("supply_center", "0001_initial"),
        ("variant", "0002_add_classical_variant"),
        ("nation", "0002_add_classical_nations"),
        ("province", "0002_add_classical_provinces"),
        ("phase", "0002_add_classical_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_supply_centers,
            remove_classical_supply_centers,
        ),
    ]
