# Generated by Django 4.2.24 on 2025-09-24 14:36

from django.db import migrations


def add_italy_vs_germany_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    # Get the Italy vs Germany variant and template phase
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    template_phase = Phase.objects.get(game=None, variant=italy_germany_variant, status="template")

    # Italy vs Germany supply centers data
    supply_centers_data = [
        {"nation": "Germany", "province": "kie"},
        {"nation": "Germany", "province": "ber"},
        {"nation": "Germany", "province": "mun"},
        {"nation": "Italy", "province": "ven"},
        {"nation": "Italy", "province": "rom"},
        {"nation": "Italy", "province": "nap"},
    ]

    # Create supply centers
    for sc_data in supply_centers_data:
        # Get the nation and province objects
        nation = Nation.objects.get(name=sc_data["nation"], variant=italy_germany_variant)
        province = Province.objects.get(province_id=sc_data["province"], variant=italy_germany_variant)
        
        SupplyCenter.objects.create(
            phase=template_phase,
            nation=nation,
            province=province,
        )


def remove_italy_vs_germany_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    template_phase = Phase.objects.get(game=None, variant=italy_germany_variant, status="template")
    SupplyCenter.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("supply_center", "0002_add_classical_supply_centers"),
        ("variant", "0003_add_italy_vs_germany_variant"),
        ("nation", "0003_add_italy_vs_germany_nations"),
        ("province", "0003_add_italy_vs_germany_provinces"),
        ("game", "0003_add_italy_vs_germany_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_supply_centers,
            remove_italy_vs_germany_supply_centers,
        ),
    ]
