# Generated by generate_variant_migrations.py on 2025-10-24 22:24:01

from django.db import migrations


def add_hundred_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    hundred_variant = Variant.objects.get(id="hundred")
    template_phase = Phase.objects.get(game=None, variant=hundred_variant, status="template")

    supply_centers_data = [{'nation': 'England', 'province': 'guy'}, {'nation': 'England', 'province': 'nom'}, {'nation': 'France', 'province': 'orl'}, {'nation': 'France', 'province': 'tou'}, {'nation': 'England', 'province': 'cal'}, {'nation': 'Burgundy', 'province': 'dij'}, {'nation': 'England', 'province': 'lon'}, {'nation': 'England', 'province': 'dev'}, {'nation': 'Burgundy', 'province': 'hol'}, {'nation': 'Burgundy', 'province': 'lux'}, {'nation': 'Burgundy', 'province': 'fla'}, {'nation': 'France', 'province': 'dau'}, {'nation': 'France', 'province': 'par'}]

    for sc_data in supply_centers_data:
        nation = Nation.objects.get(variant=hundred_variant, name=sc_data["nation"])
        province = Province.objects.get(variant=hundred_variant, province_id=sc_data["province"])

        SupplyCenter.objects.create(
            nation=nation,
            province=province,
            phase=template_phase
        )


def remove_hundred_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    hundred_variant = Variant.objects.get(id="hundred")
    template_phase = Phase.objects.get(game=None, variant=hundred_variant, status="template")
    SupplyCenter.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("supply_center", "0003_add_italy_vs_germany_supply_centers"),
        ("variant", "0004_add_hundred_variant"),
        ("nation", "0004_add_hundred_nations"),
        ("province", "0010_add_hundred_provinces"),
        ("phase", "0005_add_hundred_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_hundred_supply_centers,
            remove_hundred_supply_centers,
        ),
    ]
