# Generated by generate_variant_migrations.py on 2026-05-07 00:00:00

from django.db import migrations


def add_vietnam_war_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")
    template_phase = Phase.objects.get(game=None, variant=vietnam_war_variant, status="template")

    supply_centers_data = [{'nation': 'Thailand', 'province': 'pat'}, {'nation': 'Laos', 'province': 'nah'}, {'nation': 'Laos', 'province': 'vie'}, {'nation': 'North Vietnam', 'province': 'han'}, {'nation': 'North Vietnam', 'province': 'thn'}, {'nation': 'Cambodia', 'province': 'pre'}, {'nation': 'Cambodia', 'province': 'meo'}, {'nation': 'Thailand', 'province': 'ban'}, {'nation': 'Thailand', 'province': 'loe'}, {'nation': 'South Vietnam', 'province': 'eas'}, {'nation': 'South Vietnam', 'province': 'sag'}, {'nation': 'Laos', 'province': 'pak'}, {'nation': 'North Vietnam', 'province': 'thh'}, {'nation': 'South Vietnam', 'province': 'cam'}, {'nation': 'Cambodia', 'province': 'ang'}]

    for sc_data in supply_centers_data:
        nation = Nation.objects.get(variant=vietnam_war_variant, name=sc_data["nation"])
        province = Province.objects.get(variant=vietnam_war_variant, province_id=sc_data["province"])

        SupplyCenter.objects.create(
            nation=nation,
            province=province,
            phase=template_phase
        )


def remove_vietnam_war_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")
    template_phase = Phase.objects.get(game=None, variant=vietnam_war_variant, status="template")
    SupplyCenter.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("supply_center", "0005_add_youngstown_redux_supply_centers"),
        ("variant", "0007_add_vietnam_war_variant"),
        ("nation", "0006_add_vietnam_war_nations"),
        ("province", "0012_add_vietnam_war_provinces"),
        ("phase", "0011_add_vietnam_war_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_vietnam_war_supply_centers,
            remove_vietnam_war_supply_centers,
        ),
    ]
