# Generated by generate_variant_migrations.py on 2026-05-11 19:04:23

from django.db import migrations


def add_canton_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    canton_variant = Variant.objects.get(id="canton")
    template_phase = Phase.objects.get(game=None, variant=canton_variant, status="template")

    supply_centers_data = [{'nation': 'Turkey', 'province': 'bag'}, {'nation': 'Britain', 'province': 'cal'}, {'nation': 'Britain', 'province': 'del'}, {'nation': 'Holland', 'province': 'bor'}, {'nation': 'Japan', 'province': 'tok'}, {'nation': 'France', 'province': 'hue'}, {'nation': 'Turkey', 'province': 'con'}, {'nation': 'China', 'province': 'sha'}, {'nation': 'Holland', 'province': 'jav'}, {'nation': 'Turkey', 'province': 'dam'}, {'nation': 'Britain', 'province': 'mad'}, {'nation': 'China', 'province': 'pek'}, {'nation': 'China', 'province': 'chu'}, {'nation': 'China', 'province': 'tib'}, {'nation': 'Japan', 'province': 'sas'}, {'nation': 'France', 'province': 'han'}, {'nation': 'Holland', 'province': 'sum'}, {'nation': 'Japan', 'province': 'kyo'}, {'nation': 'Russia', 'province': 'sev'}, {'nation': 'Russia', 'province': 'kha'}, {'nation': 'Russia', 'province': 'mos'}, {'nation': 'Russia', 'province': 'irk'}, {'nation': 'France', 'province': 'sai'}]

    for sc_data in supply_centers_data:
        nation = Nation.objects.get(variant=canton_variant, name=sc_data["nation"])
        province = Province.objects.get(variant=canton_variant, province_id=sc_data["province"])

        SupplyCenter.objects.create(
            nation=nation,
            province=province,
            phase=template_phase
        )


def remove_canton_supply_centers(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    SupplyCenter = apps.get_model("supply_center", "SupplyCenter")

    canton_variant = Variant.objects.get(id="canton")
    template_phase = Phase.objects.get(game=None, variant=canton_variant, status="template")
    SupplyCenter.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("supply_center", "0006_add_vietnam_war_supply_centers"),
        ("variant", "0008_add_canton_variant"),
        ("nation", "0007_add_canton_nations"),
        ("province", "0013_add_canton_provinces"),
        ("phase", "0012_add_canton_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_canton_supply_centers,
            remove_canton_supply_centers,
        ),
    ]
