# Generated by Django 4.2.24 on 2025-09-22 20:00

from django.db import migrations


def copy_user_profiles(apps, schema_editor):
    # Get the old and new UserProfile models
    try:
        OldUserProfile = apps.get_model('game', 'UserProfile')
    except LookupError:
        # Model doesn't exist (e.g., in tests), skip migration
        return

    NewUserProfile = apps.get_model('user_profile', 'UserProfile')

    # Copy all existing user profiles
    for old_profile in OldUserProfile.objects.all():
        NewUserProfile.objects.create(
            user=old_profile.user,
            name=old_profile.name,
            picture=old_profile.picture,
        )


def reverse_copy_user_profiles(apps, schema_editor):
    # Delete all new user profiles in reverse migration
    NewUserProfile = apps.get_model('user_profile', 'UserProfile')
    NewUserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('game', '0011_drop_old_order_tables'),
    ]

    operations = [
        migrations.RunPython(copy_user_profiles, reverse_copy_user_profiles),
    ]
