# Generated by Django 4.2.25 on 2026-06-02 00:00

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='colour_profile_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_colour_profile',
            field=models.JSONField(default=user_profile.models.default_colour_profile),
        ),
    ]
