# Generated by Django 4.2.24 on 2025-09-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20250922_2000'),
    ]

    operations = [
    ]
