# Generated by Django 6.0.6 on 2026-06-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_userprofile_email_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="colorblind_mode",
            field=models.CharField(
                blank=True,
                choices=[("deuteranopia", "Deuteranopia"), ("protanopia", "Protanopia"), ("tritanopia", "Tritanopia")],
                max_length=20,
                null=True,
            ),
        ),
    ]
