# Generated by Django 6.0.6 on 2026-07-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_add_colorblind_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="colorblind_mode",
        ),
    ]
