# Generated by Django 6.0.7 on 2026-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_remove_userprofile_colorblind_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="commitment",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("undefined", "New")],
                default="undefined",
                max_length=20,
            ),
        ),
    ]
