# Generated by Django 6.0.8 on 2026-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_userprofile_commitment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetainedCommitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_hash", models.CharField(max_length=64, unique=True)),
                (
                    "commitment",
                    models.CharField(
                        choices=[("high", "High"), ("medium", "Medium"), ("low", "Low"), ("undefined", "New")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
