# Generated by Django 6.1.1 on 2026-09-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0010_userprofilepicture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_notifications_enabled",
        ),
    ]
