# Generated by Django 6.1.2 on 2026-10-08 21:05

import django.db.models.deletion
from django.db import migrations, models


def copy_pictures_into_database(apps, schema_editor):
    UserProfilePicture = apps.get_model("user_profile", "UserProfilePicture")
    UserProfilePictureContent = apps.get_model("user_profile", "UserProfilePictureContent")
    missing_ids = []
    for picture in UserProfilePicture.objects.all():
        try:
            with picture.image.open("rb") as image:
                data = image.read()
        except FileNotFoundError:
            missing_ids.append(picture.id)
            continue
        UserProfilePictureContent.objects.create(picture=picture, data=data)
    UserProfilePicture.objects.filter(id__in=missing_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0011_remove_userprofile_email_notifications_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfilePictureContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.BinaryField()),
                (
                    "picture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="user_profile.userprofilepicture",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_pictures_into_database, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="userprofilepicture",
            name="image",
        ),
    ]
