# Generated by Django 4.2.24 on 2025-09-23 15:10

from django.db import migrations


def copy_variant_data(apps, schema_editor):
    try:
        GameVariant = apps.get_model('game', 'Variant')
        VariantVariant = apps.get_model('variant', 'Variant')

        for game_variant in GameVariant.objects.all():
            VariantVariant.objects.create(
                id=game_variant.id,
                name=game_variant.name,
                description=game_variant.description,
                author=game_variant.author,
                nations_data=game_variant.nations_data,
                start_data=game_variant.start_data,
                provinces_data=game_variant.provinces_data,
                created_at=game_variant.created_at,
                updated_at=game_variant.updated_at,
            )
    except Exception:
        pass


def reverse_copy_variant_data(apps, schema_editor):
    VariantVariant = apps.get_model('variant', 'Variant')
    VariantVariant.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
        ('game', '0006_auto_20250704_2016'),
    ]

    operations = [
        migrations.RunPython(copy_variant_data, reverse_copy_variant_data),
    ]
