# Generated by Django 4.2.24 on 2025-09-24 13:55

from django.db import migrations


def add_classical_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.create(
        id="classical", name="Classical", description="The original game of Diplomacy", author="Allan B. Calhamer"
    )


def remove_classical_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.filter(id="classical").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_variant,
            remove_classical_variant,
        ),
    ]
