# Generated by Django 4.2.24 on 2025-09-23 15:17

from django.db import migrations


def add_classical_variant(apps, schema_editor):
    Variant = apps.get_model('variant', 'Variant')
    if not Variant.objects.filter(id="classical").exists():
        Variant.objects.create(
            id="classical",
            name="Classical",
            description="The standard diplomacy variant.",
            author="Allan B. Calhamer",
            nations_data=[
                {"name": "England", "color": "#FF0000"},
                {"name": "France", "color": "#0000FF"},
                {"name": "Germany", "color": "#000000"},
                {"name": "Italy", "color": "#00FF00"},
                {"name": "Austria", "color": "#FFFF00"},
                {"name": "Turkey", "color": "#FF00FF"},
                {"name": "Russia", "color": "#FFFFFF"}
            ],
            start_data={
                "season": "Spring",
                "year": "1901",
                "type": "Movement",
                "units": [],
                "supply_centers": []
            },
            provinces_data=[]
        )


def remove_classical_variant(apps, schema_editor):
    Variant = apps.get_model('variant', 'Variant')
    Variant.objects.filter(id="classical").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_copy_variant_data'),
    ]

    operations = [
        migrations.RunPython(
            add_classical_variant,
            remove_classical_variant,
        ),
    ]
