# Generated by Django 4.2.24 on 2025-09-24 14:33

from django.db import migrations


def add_italy_vs_germany_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.create(
        id="italy-vs-germany",
        name="Italy vs Germany",
        description="A two player variant on the classical map.",
        author="Allan B. Calhamer",
    )


def remove_italy_vs_germany_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.filter(id="italy-vs-germany").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0002_add_classical_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_variant,
            remove_italy_vs_germany_variant,
        ),
    ]
