# Generated by Django 4.2.24 on 2025-09-23 15:18

from django.db import migrations


def add_italy_vs_germany_variant(apps, schema_editor):
    Variant = apps.get_model('variant', 'Variant')
    if not Variant.objects.filter(id="italy-vs-germany").exists():
        Variant.objects.create(
            id="italy-vs-germany",
            name="Italy vs Germany",
            description="A two-player variant focusing on Italy and Germany.",
            author="Unknown",
            nations_data=[
                {"name": "Italy", "color": "#00FF00"},
                {"name": "Germany", "color": "#000000"}
            ],
            start_data={
                "season": "Spring",
                "year": "1901",
                "type": "Movement",
                "units": [],
                "supply_centers": []
            },
            provinces_data=[]
        )


def remove_italy_vs_germany_variant(apps, schema_editor):
    Variant = apps.get_model('variant', 'Variant')
    Variant.objects.filter(id="italy-vs-germany").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0003_add_classical_variant'),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_variant,
            remove_italy_vs_germany_variant,
        ),
    ]
