# Generated by generate_variant_migrations.py on 2025-10-24 22:24:01

from django.db import migrations


def add_hundred_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.create(
        id="hundred",
        name="Hundred",
        description="""The Hundred Years' War was a series of conflicts from 1337 to 1453, waged between the English House of Plantagenet and the French House of Valois, over the Kingdom of France.""",
        author="Andy Schwarz"
    )


def remove_hundred_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.filter(id="hundred").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0003_add_italy_vs_germany_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_hundred_variant,
            remove_hundred_variant,
        ),
    ]
