# Generated by Django 4.2.26 on 2025-11-28 13:15

from django.db import migrations, models


def populate_solo_victory_sc_counts(apps, schema_editor):
    Variant = apps.get_model('variant', 'Variant')

    sc_counts = {
        'Classical': 18,
        'Italy vs Germany': 18,
        'North Sea Wars': 8,
    }

    for name, count in sc_counts.items():
        Variant.objects.filter(name=name).update(solo_victory_sc_count=count)


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0004_add_hundred_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='solo_victory_sc_count',
            field=models.IntegerField(default=18),
        ),
        migrations.RunPython(populate_solo_victory_sc_counts, migrations.RunPython.noop),
    ]
