# Generated by Django 4.2.24 on 2025-09-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0005_create_template_phases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='start_data',
        ),
    ]
