# Generated by generate_variant_migrations.py on 2026-03-28 21:21:09

from django.db import migrations


def add_youngstown_redux_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.create(
        id="youngstown-redux",
        name="Youngstown Redux",
        description="""China, India and Japan join the standard seven nations.""",
        author="airborne"
    )


def remove_youngstown_redux_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.filter(id="youngstown-redux").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0005_variant_solo_victory_sc_count"),
    ]

    operations = [
        migrations.RunPython(
            add_youngstown_redux_variant,
            remove_youngstown_redux_variant,
        ),
    ]
