# Generated by Django 4.2.24 on 2025-09-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0006_remove_start_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='provinces_data',
        ),
    ]
