# Generated by generate_variant_migrations.py on 2026-05-07 00:00:00

from django.db import migrations


def add_vietnam_war_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.create(
        id="vietnam-war",
        name="Vietnam War",
        description="""The Indochina Peninsula in 1955: the beginning of Vietnam War.""",
        author="ThePolice",
        solo_victory_sc_count=13,
    )


def remove_vietnam_war_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.filter(id="vietnam-war").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0006_add_youngstown_redux_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_vietnam_war_variant,
            remove_vietnam_war_variant,
        ),
    ]
