# Generated by generate_variant_migrations.py on 2026-05-11 19:04:23

from django.db import migrations


def add_canton_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.create(
        id="canton",
        name="Canton",
        description="""Asia at the beginning of the 20th century. It's fate is determined by Britain, China, France, Holland, Japan, Russia, and Turkey.""",
        author="Paul Webb",
        solo_victory_sc_count=19,
    )


def remove_canton_variant(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Variant.objects.filter(id="canton").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0007_add_vietnam_war_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_canton_variant,
            remove_canton_variant,
        ),
    ]
