# Generated by Django 4.2.24 on 2025-09-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0007_remove_provinces_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='nations_data',
        ),
    ]
