# Generated by Django 4.2.30 on 2026-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0007_add_vietnam_war_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='json_definition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
