# Generated by Django 4.2.30 on 2026-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0008_add_canton_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='adjudication_modifiers',
            field=models.JSONField(default=list),
        ),
    ]
