# Generated by Django 4.2.30 on 2026-05-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0013_convert_victory_conditions_to_list'),
        ('variant', '0014_backfill_variant_svgs'),
    ]

    operations = [
    ]
