# Generated by Django 4.2.30 on 2026-05-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0015_correct_hundred_phase_progression'),
        ('variant', '0015_merge_20260517_1923'),
    ]

    operations = [
    ]
