# Generated by Django 6.0.6 on 2026-06-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0024_widen_variant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="adjudication_modifiers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="variant",
            name="dominance_rules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
