# Generated by Django 6.1 on 2026-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variant", "0024_widen_variant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="unit_scaling",
            field=models.FloatField(default=1),
        ),
    ]
