# Generated by Django 6.0.7 on 2026-07-28 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channel", "0005_channelevent"),
        ("member", "0007_member_seeking_replacement_replaced_by"),
        ("phase", "0016_phase_resolution_job_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("plan", "Plan"), ("finalize", "Finalize"), ("reply", "Reply")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="agent_tasks", to="member.member"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="channel.channelmessage",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="phase.phase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("message__isnull", True)),
                        fields=("kind", "member", "phase"),
                        name="unique_phase_agent_task",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("message__isnull", False)),
                        fields=("kind", "member", "message"),
                        name="unique_reply_agent_task",
                    ),
                ],
            },
        ),
    ]
