version: "3.9"
services:
  development:
    container_name: diplicity-development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/native
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - diplicity-network
    tty: true

  codegen:
    container_name: diplicity-codegen
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/web/node_modules
      - /app/packages/native
    env_file:
      - .env
    networks:
      - diplicity-network
    depends_on:
      - service
    command: >
      sh -c " python3 service/manage.py spectacular --file service/openapi-schema.yaml && npx --yes @rtk-query/codegen-openapi openapi-config.cjs"

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules
    container_name: diplicity-web
    entrypoint: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    volumes:
      - ./packages/web:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - diplicity-network

  service:
    container_name: diplicity-service
    build:
      context: ./service
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=True
      - ROOT_LOG_LEVEL=INFO
      - DJANGO_LOG_LEVEL=INFO
      - DB_LOG_LEVEL=WARNING
      - GAME_LOG_LEVEL=INFO
    working_dir: /app/service
    command: >
      sh -c " python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - diplicity-network
    tty: true

  test-service:
    container_name: diplicity-test-service
    build:
      context: ./service
      dockerfile: Dockerfile
      target: development
    command: >
      sh -c "python3 -m pytest"
    networks:
      - diplicity-network
    environment:
      DATABASE_NAME: diplicity
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  db:
    container_name: diplicity-db
    image: postgres:13
    environment:
      POSTGRES_DB: diplicity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - diplicity-network

  phase-resolver:
    build:
      context: ./service
      dockerfile: Dockerfile
      target: development
    container_name: diplicity-phase-resolver
    working_dir: /app/service
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=True
      - ROOT_LOG_LEVEL=INFO
      - DJANGO_LOG_LEVEL=INFO
      - DB_LOG_LEVEL=WARNING
      - GAME_LOG_LEVEL=INFO
    command: >
      sh -c 'while true; do python manage.py resolve_due_phases; sleep 60; done'
    networks:
      - diplicity-network
    depends_on:
      - db

networks:
  diplicity-network:
    name: diplicity-network

volumes:
  postgres_data:
