# Generated by Django 4.2.30 on 2026-05-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phase', '0012_add_canton_template_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowAdjudicationDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3')], max_length=10)),
                ('pre_state', models.JSONField()),
                ('godip_response', models.JSONField()),
                ('python_response', models.JSONField()),
                ('diff_summary', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_adjudication_diffs', to='phase.phase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
