# Generated by Django 4.2.24 on 2025-09-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = []
