# Generated by Django 4.2.26 on 2025-11-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0004_game_sandbox_alter_game_movement_phase_duration'),
        ('phase', '0008_fix_year_season_to_spring'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='victory', to='game.game')),
                ('members', models.ManyToManyField(related_name='victories', to='member.member')),
                ('winning_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.phase')),
            ],
            options={
                'verbose_name_plural': 'Victories',
            },
        ),
    ]
