# Generated by Django 4.2.26 on 2025-11-28 15:30

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def fix_status_values(apps, schema_editor):
    Game = apps.get_model("game", "Game")
    Phase = apps.get_model("phase", "Phase")

    games_fixed = 0
    phases_fixed = 0

    invalid_status_values = [None, "Completed", ""]

    games_to_fix = Game.objects.filter(status__in=invalid_status_values)
    games_count = games_to_fix.count()

    if games_count > 0:
        logger.info(f"Found {games_count} games with invalid status values")
        games_to_fix.update(status="completed")
        games_fixed = games_count
        logger.info(f"Fixed {games_fixed} game status values to 'completed'")

    phases_to_fix = Phase.objects.filter(status__in=invalid_status_values)
    phases_count = phases_to_fix.count()

    if phases_count > 0:
        logger.info(f"Found {phases_count} phases with invalid status values")
        phases_to_fix.update(status="completed")
        phases_fixed = phases_count
        logger.info(f"Fixed {phases_fixed} phase status values to 'completed'")

    logger.info(
        f"Migration complete: {games_fixed} games fixed, {phases_fixed} phases fixed"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("victory", "0002_apply_solo_victories_to_existing_games"),
        ("game", "0004_game_sandbox_alter_game_movement_phase_duration"),
        ("phase", "0009_revert_year_season_fix"),
    ]

    operations = [
        migrations.RunPython(
            fix_status_values,
            reverse_code=migrations.RunPython.noop
        ),
    ]
