# Generated by Django 4.2.24 on 2025-09-24 14:34

from django.db import migrations


def add_italy_vs_germany_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    # Get the Italy vs Germany variant
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")

    # Create template phase for Italy vs Germany
    Phase.objects.create(
        game=None,
        variant=italy_germany_variant,
        status="template",
        season="Spring",
        year=1901,
        type="Movement",
        ordinal=1,
    )


def remove_italy_vs_germany_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    Phase.objects.filter(game=None, variant=italy_germany_variant, status="template").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0002_add_classical_template_phase"),
        ("variant", "0003_add_italy_vs_germany_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_template_phase,
            remove_italy_vs_germany_template_phase,
        ),
    ]