# Generated by Django 4.2.24 on 2025-09-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0003_add_italy_vs_germany_template_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['ordinal']},
        ),
    ]
