# Generated by generate_variant_migrations.py on 2025-10-24 22:24:01

from django.db import migrations


def add_hundred_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    hundred_variant = Variant.objects.get(id="hundred")

    Phase.objects.create(
        game=None,
        variant=hundred_variant,
        status="template",
        season="Year",
        year=1425,
        type="Movement",
        ordinal=1,
    )


def remove_hundred_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    hundred_variant = Variant.objects.get(id="hundred")
    Phase.objects.filter(game=None, variant=hundred_variant, status="template").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0004_alter_phase_options"),
        ("variant", "0004_add_hundred_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_hundred_template_phase,
            remove_hundred_template_phase,
        ),
    ]
