# Generated by Django 4.2.25 on 2025-11-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0005_add_hundred_template_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasestate',
            name='has_possible_orders',
            field=models.BooleanField(default=False),
        ),
    ]
