# Generated by Django 4.2.25 on 2025-11-14 16:42

from django.db import migrations


def fix_year_season_to_spring(apps, schema_editor):
    Phase = apps.get_model("phase", "Phase")

    # Update all phases with season="Year" to season="Spring"
    Phase.objects.filter(season="Year").update(season="Spring")


def revert_spring_season_to_year(apps, schema_editor):
    Phase = apps.get_model("phase", "Phase")

    # Revert all phases with season="Spring" that were created from hundred variant
    # We only revert the hundred variant template phase as other phases might have legitimately been Spring
    Variant = apps.get_model("variant", "Variant")

    try:
        hundred_variant = Variant.objects.get(id="hundred")
        Phase.objects.filter(variant=hundred_variant, season="Spring").update(season="Year")
    except Variant.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0007_backfill_has_possible_orders"),
    ]

    operations = [
        migrations.RunPython(
            fix_year_season_to_spring,
            revert_spring_season_to_year,
        ),
    ]
