# Generated by generate_variant_migrations.py on 2026-03-28 21:21:09

from django.db import migrations


def add_youngstown_redux_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    youngstown_redux_variant = Variant.objects.get(id="youngstown-redux")

    Phase.objects.create(
        game=None,
        variant=youngstown_redux_variant,
        status="template",
        season="Spring",
        year=1901,
        type="Movement",
        ordinal=1,
    )


def remove_youngstown_redux_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    youngstown_redux_variant = Variant.objects.get(id="youngstown-redux")
    Phase.objects.filter(game=None, variant=youngstown_redux_variant, status="template").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0009_revert_year_season_fix"),
        ("variant", "0006_add_youngstown_redux_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_youngstown_redux_template_phase,
            remove_youngstown_redux_template_phase,
        ),
    ]
