# Generated by generate_variant_migrations.py on 2026-05-07 00:00:00

from django.db import migrations


def add_vietnam_war_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")

    Phase.objects.create(
        game=None,
        variant=vietnam_war_variant,
        status="template",
        season="Spring",
        year=1955,
        type="Movement",
        ordinal=1,
    )


def remove_vietnam_war_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")
    Phase.objects.filter(game=None, variant=vietnam_war_variant, status="template").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0010_add_youngstown_redux_template_phase"),
        ("variant", "0007_add_vietnam_war_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_vietnam_war_template_phase,
            remove_vietnam_war_template_phase,
        ),
    ]
