# Generated by generate_variant_migrations.py on 2026-05-11 19:04:23

from django.db import migrations


def add_canton_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    canton_variant = Variant.objects.get(id="canton")

    Phase.objects.create(
        game=None,
        variant=canton_variant,
        status="template",
        season="Spring",
        year=1901,
        type="Movement",
        ordinal=1,
    )


def remove_canton_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    canton_variant = Variant.objects.get(id="canton")
    Phase.objects.filter(game=None, variant=canton_variant, status="template").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0011_add_vietnam_war_template_phase"),
        ("variant", "0008_add_canton_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_canton_template_phase,
            remove_canton_template_phase,
        ),
    ]
