# Generated by Django 4.2.30 on 2026-06-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0012_add_canton_template_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasestate',
            name='deadline_warning_sent_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
