# Generated by Django 6.0.6 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0015_backfill_orders_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="resolution_job_id",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
