# Generated by Django 6.0.7 on 2026-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0016_phase_resolution_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="phase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("template", "Template"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
