# Generated by Django 6.1 on 2026-08-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase", "0019_unique_live_phase_ordinal_per_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="contested_provinces",
            field=models.JSONField(default=list),
        ),
    ]
