# Generated by Django 6.0.7 on 2026-08-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(choices=[("eval", "Eval"), ("match", "Match")], default="eval", max_length=20),
                ),
                ("model", models.CharField(max_length=255)),
                ("commit", models.CharField(max_length=40)),
                ("dataset", models.CharField(blank=True, max_length=12)),
                ("epochs", models.PositiveIntegerField(blank=True, null=True)),
                ("eval_id", models.CharField(blank=True, max_length=64)),
                ("ran_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="EvalScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scorer", models.CharField(max_length=100)),
                ("metric", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("stderr", models.FloatField(blank=True, null=True)),
                ("sample_count", models.PositiveIntegerField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scores", to="harness.evalrun"
                    ),
                ),
            ],
            options={
                "ordering": ["run_id", "scorer", "metric"],
                "constraints": [
                    models.UniqueConstraint(fields=("run", "scorer", "metric"), name="unique_run_scorer_metric")
                ],
            },
        ),
    ]
