# Generated by Django 4.2.24 on 2025-09-24 14:18

from django.db import migrations
from common.constants import PhaseStatus


def add_classical_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("game", "Phase")

    # Get the classical variant
    classical_variant = Variant.objects.get(id="classical")

    # Create template phase
    Phase.objects.create(
        game=None,  # Template phases don't belong to games
        variant=classical_variant,
        ordinal=0,  # All template phases have ordinal 0
        status=PhaseStatus.TEMPLATE,
        season="Spring",
        year=1901,
        type="Movement",
        scheduled_resolution=None,
        options=None,
    )


def remove_classical_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("game", "Phase")

    classical_variant = Variant.objects.get(id="classical")
    # Delete all template phases for classical variant
    Phase.objects.filter(game=None, variant=classical_variant, status=PhaseStatus.TEMPLATE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("variant", "0002_add_classical_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_template_phase,
            remove_classical_template_phase,
        ),
    ]
