# Generated by Django 4.2.25 on 2025-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='movement_phase_duration',
            field=models.CharField(choices=[('24 hours', '24 hours'), ('48 hours', '48 hours')], default='24 hours', max_length=20),
        ),
    ]
