# Generated by Django 4.2.24 on 2025-09-24 14:02

from django.db import migrations


def add_classical_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    # Get the classical variant
    classical_variant = Variant.objects.get(id="classical")

    # Create template phase for classical
    Phase.objects.create(
        game=None,
        variant=classical_variant,
        status="template",
        season="Spring",
        year=1901,
        type="Movement",
        ordinal=1,
    )


def remove_classical_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")

    classical_variant = Variant.objects.get(id="classical")
    Phase.objects.filter(game=None, variant=classical_variant, status="template").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("variant", "0002_add_classical_variant"),
        ("phase", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_template_phase,
            remove_classical_template_phase,
        ),
    ]
