# Generated by Django 4.2.20 on 2025-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='dislodged_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
