# Generated by Django 4.2.20 on 2025-04-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_phase_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('bounced', 'Bounced')], max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='game.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
