# Generated by Django 4.2.23 on 2025-06-18 16:28

from django.db import migrations


def add_italy_vs_germany_variant(apps, schema_editor):
    Variant = apps.get_model('game', 'Variant')
    Variant.objects.create(
        name="Italy vs Germany",
        id="italy-vs-germany",
    )


def remove_italy_vs_germany_variant(apps, schema_editor):
    Variant = apps.get_model('game', 'Variant')
    Variant.objects.filter(id="italy-vs-germany").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_classical_variant'),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_variant,
            remove_italy_vs_germany_variant,
        ),
    ]
