# Generated by Django 4.2.24 on 2025-09-24 14:34

from django.db import migrations
from common.constants import PhaseStatus


def add_italy_vs_germany_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("game", "Phase")

    # Get the Italy vs Germany variant
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")

    # Create template phase
    Phase.objects.create(
        game=None,  # Template phases don't belong to games
        variant=italy_germany_variant,
        ordinal=0,  # All template phases have ordinal 0
        status=PhaseStatus.TEMPLATE,
        season="Spring",
        year=1901,
        type="Movement",
        scheduled_resolution=None,
        options=None,
    )


def remove_italy_vs_germany_template_phase(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("game", "Phase")

    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    # Delete all template phases for Italy vs Germany variant
    Phase.objects.filter(game=None, variant=italy_germany_variant, status=PhaseStatus.TEMPLATE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_add_classical_template_phase"),
        ("variant", "0003_add_italy_vs_germany_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_template_phase,
            remove_italy_vs_germany_template_phase,
        ),
    ]
