# Generated by Django 4.2.21 on 2025-05-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_unit_dislodged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresolution',
            name='by',
            field=models.CharField(blank=True, help_text='Province that caused the resolution status (e.g. province that caused a bounce)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderresolution',
            name='status',
            field=models.CharField(choices=[('OK', 'Succeeded'), ('ErrIllegalMove', 'Illegal move'), ('ErrIllegalDestination', 'Illegal destination'), ('ErrBounce', 'Bounced'), ('ErrInvalidSupporteeOrder', 'Invalid support order'), ('ErrIllegalSupportDestination', 'Illegal support destination'), ('ErrInvalidDestination', 'Invalid destination')], max_length=30),
        ),
    ]
