# Generated by Django 4.2.25 on 2025-10-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_movement_phase_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='movement_phase_duration',
            field=models.CharField(choices=[('24 hours', '24 hours'), ('48 hours', '48 hours'), ('1 week', '1 week')], default='24 hours', max_length=20),
        ),
    ]
