# Generated by Django 4.2.20 on 2025-04-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_orderresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='resolution_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='game.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
