# Generated by Django 4.2.23 on 2025-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_add_italy_vs_germany_variant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status'], name='game_game_status_295efa_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['variant'], name='game_game_variant_24352b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['game', 'user'], name='game_member_game_id_1d3341_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='game_member_user_id_5c13f1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['game'], name='game_member_game_id_5157f3_idx'),
        ),
    ]
