# Generated by Django 4.2.24 on 2025-09-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0003_add_italy_vs_germany_nations'),
        ('game', '0003_add_italy_vs_germany_template_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='nation.nation'),
        ),
    ]
