# Generated by Django 4.2.21 on 2025-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_orderresolution_by_alter_orderresolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nation_assignment',
            field=models.CharField(choices=[('random', 'Random'), ('ordered', 'Ordered')], default='random', max_length=20),
        ),
    ]
