# Generated by Django 4.2.25 on 2025-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_movement_phase_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='movement_phase_duration',
            field=models.CharField(blank=True, choices=[('24 hours', '24 hours'), ('48 hours', '48 hours'), ('1 week', '1 week')], default='24 hours', max_length=20, null=True),
        ),
    ]
