# Generated by Django 4.2.23 on 2025-07-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_game_game_status_295efa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasestate',
            name='options',
        ),
        migrations.AddField(
            model_name='phase',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
