# Generated by Django 4.2.27 on 2026-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_sandbox_alter_game_movement_phase_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
    ]
