# Generated by Django 4.2.23 on 2025-07-04 20:16

from django.db import migrations, models


def migrate_variant_data(apps, schema_editor):
    Variant = apps.get_model("game", "Variant")

    # Classical variant data
    classical_data = {
        "description": "The original game of Diplomacy",
        "author": "Allan B. Calhamer",
        "nations": [
            {"name": "England", "color": "#2196F3"},
            {"name": "France", "color": "#80DEEA"},
            {"name": "Germany", "color": "#90A4AE"},
            {"name": "Italy", "color": "#4CAF50"},
            {"name": "Austria", "color": "#F44336"},
            {"name": "Turkey", "color": "#FFC107"},
            {"name": "Russia", "color": "#F5F5F5"},
        ],
        "start": {
            "year": 1901,
            "season": "Spring",
            "type": "Movement",
            "units": [
                {"type": "Fleet", "nation": "England", "province": "edi"},
                {"type": "Army", "nation": "England", "province": "lvp"},
                {"type": "Fleet", "nation": "England", "province": "lon"},
                {"type": "Fleet", "nation": "France", "province": "bre"},
                {"type": "Army", "nation": "France", "province": "par"},
                {"type": "Army", "nation": "France", "province": "mar"},
                {"type": "Fleet", "nation": "Germany", "province": "kie"},
                {"type": "Army", "nation": "Germany", "province": "ber"},
                {"type": "Army", "nation": "Germany", "province": "mun"},
                {"type": "Army", "nation": "Italy", "province": "ven"},
                {"type": "Army", "nation": "Italy", "province": "rom"},
                {"type": "Fleet", "nation": "Italy", "province": "nap"},
                {"type": "Fleet", "nation": "Austria", "province": "tri"},
                {"type": "Army", "nation": "Austria", "province": "vie"},
                {"type": "Army", "nation": "Austria", "province": "bud"},
                {"type": "Fleet", "nation": "Russia", "province": "stp/sc"},
                {"type": "Army", "nation": "Russia", "province": "mos"},
                {"type": "Army", "nation": "Russia", "province": "war"},
                {"type": "Fleet", "nation": "Russia", "province": "sev"},
                {"type": "Army", "nation": "Turkey", "province": "con"},
                {"type": "Army", "nation": "Turkey", "province": "smy"},
                {"type": "Fleet", "nation": "Turkey", "province": "ank"},
            ],
            "supply_centers": [
                {"nation": "England", "province": "edi"},
                {"nation": "England", "province": "lvp"},
                {"nation": "England", "province": "lon"},
                {"nation": "France", "province": "bre"},
                {"nation": "France", "province": "par"},
                {"nation": "France", "province": "mar"},
                {"nation": "Germany", "province": "kie"},
                {"nation": "Germany", "province": "ber"},
                {"nation": "Germany", "province": "mun"},
                {"nation": "Italy", "province": "ven"},
                {"nation": "Italy", "province": "rom"},
                {"nation": "Italy", "province": "nap"},
                {"nation": "Austria", "province": "tri"},
                {"nation": "Austria", "province": "vie"},
                {"nation": "Austria", "province": "bud"},
                {"nation": "Turkey", "province": "con"},
                {"nation": "Turkey", "province": "ank"},
                {"nation": "Turkey", "province": "smy"},
                {"nation": "Russia", "province": "sev"},
                {"nation": "Russia", "province": "mos"},
                {"nation": "Russia", "province": "stp"},
                {"nation": "Russia", "province": "war"},
            ],
        },
        "provinces": [
            {
                "id": "adr",
                "name": "Adriatic Sea",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "aeg", "name": "Aegean Sea", "supply_center": False, "type": "sea"},
            {"id": "alb", "name": "Albania", "supply_center": False, "type": "coastal"},
            {"id": "ank", "name": "Ankara", "supply_center": True, "type": "coastal"},
            {"id": "apu", "name": "Apulia", "supply_center": False, "type": "coastal"},
            {"id": "arm", "name": "Armenia", "supply_center": False, "type": "coastal"},
            {"id": "bal", "name": "Baltic Sea", "supply_center": False, "type": "sea"},
            {"id": "bar", "name": "Barents Sea", "supply_center": False, "type": "sea"},
            {"id": "bel", "name": "Belgium", "supply_center": True, "type": "coastal"},
            {"id": "ber", "name": "Berlin", "supply_center": True, "type": "coastal"},
            {"id": "bla", "name": "Black Sea", "supply_center": False, "type": "sea"},
            {"id": "boh", "name": "Bohemia", "supply_center": False, "type": "land"},
            {"id": "bre", "name": "Brest", "supply_center": True, "type": "coastal"},
            {"id": "bud", "name": "Budapest", "supply_center": True, "type": "land"},
            {"id": "bul", "name": "Bulgaria", "supply_center": True, "type": "coastal"},
            {
                "id": "bul/ec",
                "name": "Bulgaria (EC)",
                "supply_center": False,
                "type": "sea",
            },
            {
                "id": "bul/sc",
                "name": "Bulgaria (SC)",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "bur", "name": "Burgundy", "supply_center": False, "type": "land"},
            {"id": "cly", "name": "Clyde", "supply_center": False, "type": "coastal"},
            {
                "id": "con",
                "name": "Constantinople",
                "supply_center": True,
                "type": "coastal",
            },
            {"id": "den", "name": "Denmark", "supply_center": True, "type": "coastal"},
            {
                "id": "edi",
                "name": "Edinburgh",
                "supply_center": True,
                "type": "coastal",
            },
            {
                "id": "eng",
                "name": "English Channel",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "fin", "name": "Finland", "supply_center": False, "type": "coastal"},
            {"id": "gal", "name": "Galicia", "supply_center": False, "type": "land"},
            {"id": "gas", "name": "Gascony", "supply_center": False, "type": "coastal"},
            {
                "id": "gol",
                "name": "Gulf of Lyon",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "gre", "name": "Greece", "supply_center": True, "type": "coastal"},
            {
                "id": "hel",
                "name": "Heligoland Bight",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "hol", "name": "Holland", "supply_center": True, "type": "coastal"},
            {"id": "ion", "name": "Ionian Sea", "supply_center": False, "type": "sea"},
            {"id": "iri", "name": "Irish Sea", "supply_center": False, "type": "sea"},
            {"id": "kie", "name": "Kiel", "supply_center": True, "type": "coastal"},
            {"id": "lon", "name": "London", "supply_center": True, "type": "coastal"},
            {"id": "lvn", "name": "Livonia", "supply_center": False, "type": "coastal"},
            {
                "id": "lvp",
                "name": "Liverpool",
                "supply_center": True,
                "type": "coastal",
            },
            {
                "id": "mar",
                "name": "Marseilles",
                "supply_center": True,
                "type": "coastal",
            },
            {
                "id": "mid",
                "name": "Mid-Atlantic",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "mos", "name": "Moscow", "supply_center": True, "type": "land"},
            {"id": "mun", "name": "Munich", "supply_center": True, "type": "land"},
            {
                "id": "naf",
                "name": "North Africa",
                "supply_center": False,
                "type": "coastal",
            },
            {
                "id": "nat",
                "name": "North Atlantic",
                "supply_center": False,
                "type": "sea",
            },
            {
                "id": "nrg",
                "name": "Norwegian Sea",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "nth", "name": "North Sea", "supply_center": False, "type": "sea"},
            {"id": "nwy", "name": "Norway", "supply_center": True, "type": "coastal"},
            {"id": "par", "name": "Paris", "supply_center": True, "type": "land"},
            {"id": "pic", "name": "Picardy", "supply_center": False, "type": "coastal"},
            {
                "id": "pie",
                "name": "Piedmont",
                "supply_center": False,
                "type": "coastal",
            },
            {"id": "por", "name": "Portugal", "supply_center": True, "type": "coastal"},
            {"id": "pru", "name": "Prussia", "supply_center": False, "type": "coastal"},
            {"id": "rom", "name": "Rome", "supply_center": True, "type": "coastal"},
            {"id": "ruh", "name": "Ruhr", "supply_center": False, "type": "land"},
            {"id": "rum", "name": "Rumania", "supply_center": True, "type": "coastal"},
            {"id": "ser", "name": "Serbia", "supply_center": True, "type": "land"},
            {
                "id": "sev",
                "name": "Sevastopol",
                "supply_center": True,
                "type": "coastal",
            },
            {"id": "sil", "name": "Silesia", "supply_center": False, "type": "land"},
            {
                "id": "ska",
                "name": "Skagerakk (SKA)",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "smy", "name": "Smyrna", "supply_center": True, "type": "coastal"},
            {"id": "spa", "name": "Spain", "supply_center": True, "type": "coastal"},
            {
                "id": "spa/nc",
                "name": "Spain (NC)",
                "supply_center": False,
                "type": "sea",
            },
            {
                "id": "spa/sc",
                "name": "Spain (SC)",
                "supply_center": False,
                "type": "sea",
            },
            {
                "id": "stp",
                "name": "St. Petersburg",
                "supply_center": True,
                "type": "coastal",
            },
            {
                "id": "stp/nc",
                "name": "St. Petersburg (NC)",
                "supply_center": False,
                "type": "sea",
            },
            {
                "id": "stp/sc",
                "name": "St. Petersburg (SC)",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "swe", "name": "Sweden", "supply_center": True, "type": "coastal"},
            {"id": "syr", "name": "Syria", "supply_center": False, "type": "coastal"},
            {"id": "tri", "name": "Trieste", "supply_center": True, "type": "coastal"},
            {"id": "tun", "name": "Tunis", "supply_center": True, "type": "coastal"},
            {"id": "tus", "name": "Tuscany", "supply_center": False, "type": "coastal"},
            {
                "id": "tys",
                "name": "Tyrrhenian Sea",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "ukr", "name": "Ukraine", "supply_center": False, "type": "land"},
            {"id": "ven", "name": "Venice", "supply_center": True, "type": "coastal"},
            {"id": "vie", "name": "Vienna", "supply_center": True, "type": "land"},
            {"id": "wal", "name": "Wales", "supply_center": False, "type": "coastal"},
            {"id": "war", "name": "Warsaw", "supply_center": True, "type": "land"},
            {
                "id": "wes",
                "name": "West Mediterranean",
                "supply_center": False,
                "type": "sea",
            },
            {
                "id": "yor",
                "name": "Yorkshire",
                "supply_center": False,
                "type": "coastal",
            },
            {
                "id": "bot",
                "name": "Gulf of Bothnia",
                "supply_center": False,
                "type": "sea",
            },
            {"id": "tyr", "name": "Tyrolia", "supply_center": False, "type": "land"},
            {"id": "eas", "name": "East Med", "supply_center": False, "type": "sea"},
            {"id": "nap", "name": "Naples", "supply_center": True, "type": "coastal"},
        ],
    }

    # Italy vs Germany variant data
    italy_germany_data = {
        "description": "A two player variant on the classical map.",
        "author": "Allan B. Calhamer",
        "nations": [
            {"name": "Germany", "color": "#90A4AE"},
            {"name": "Italy", "color": "#4CAF50"},
        ],
        "start": {
            "year": 1901,
            "season": "Spring",
            "type": "Movement",
            "units": [
                {"type": "Fleet", "nation": "Germany", "province": "kie"},
                {"type": "Army", "nation": "Germany", "province": "ber"},
                {"type": "Army", "nation": "Germany", "province": "mun"},
                {"type": "Army", "nation": "Italy", "province": "ven"},
                {"type": "Army", "nation": "Italy", "province": "rom"},
                {"type": "Fleet", "nation": "Italy", "province": "nap"},
            ],
            "supply_centers": [
                {"nation": "Germany", "province": "kie"},
                {"nation": "Germany", "province": "ber"},
                {"nation": "Germany", "province": "mun"},
                {"nation": "Italy", "province": "ven"},
                {"nation": "Italy", "province": "rom"},
                {"nation": "Italy", "province": "nap"},
            ],
        },
        "provinces": classical_data["provinces"],  # Same provinces as classical
    }

    # Update or create variants
    classical_variant, _ = Variant.objects.update_or_create(
        id="classical",
        defaults={
            "name": "Classical",
            "description": classical_data["description"],
            "author": classical_data["author"],
            "nations_data": classical_data["nations"],
            "start_data": classical_data["start"],
            "provinces_data": classical_data["provinces"],
        },
    )

    italy_germany_variant, _ = Variant.objects.update_or_create(
        id="italy-vs-germany",
        defaults={
            "name": "Italy vs Germany",
            "description": italy_germany_data["description"],
            "author": italy_germany_data["author"],
            "nations_data": italy_germany_data["nations"],
            "start_data": italy_germany_data["start"],
            "provinces_data": italy_germany_data["provinces"],
        },
    )


def reverse_migrate_variant_data(apps, schema_editor):
    # If you need to reverse this migration, you could remove the JSON data
    # and revert to the old file-based approach
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_remove_phasestate_options_phase_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="variant",
            name="author",
            field=models.CharField(max_length=200, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="variant",
            name="nations_data",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="variant",
            name="start_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="variant",
            name="provinces_data",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(migrate_variant_data, reverse_migrate_variant_data),
    ]
