# Generated by Django 4.2.27 on 2026-02-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_abandoned_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='movement_phase_duration',
            field=models.CharField(blank=True, choices=[('1 hour', '1 hour'), ('12 hours', '12 hours'), ('24 hours', '24 hours'), ('48 hours', '48 hours'), ('3 days', '3 days'), ('4 days', '4 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks')], default='24 hours', max_length=20, null=True),
        ),
    ]
