# Generated by Django 4.2.23 on 2025-07-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20250704_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='resolution_task',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='remaining_time',
        ),
        migrations.AddField(
            model_name='phase',
            name='scheduled_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='nations_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='provinces_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='start_data',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
