# Generated by Django 4.2.27 on 2026-02-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_movement_phase_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='retreat_phase_duration',
            field=models.CharField(blank=True, choices=[('1 hour', '1 hour'), ('12 hours', '12 hours'), ('24 hours', '24 hours'), ('48 hours', '48 hours'), ('3 days', '3 days'), ('4 days', '4 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks')], max_length=20, null=True),
        ),
    ]
