# Generated by Django 4.2.23 on 2025-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_game_resolution_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Fleet', 'Fleet'), ('Army', 'Army')], max_length=10),
        ),
    ]
