# Generated by Django 4.2.27 on 2026-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_add_retreat_phase_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
