# Generated by Django 4.2.23 on 2025-09-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Army', 'Army'), ('Fleet', 'Fleet')], max_length=50, null=True),
        ),
    ]
