# Generated by Django 4.2.24 on 2025-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_order_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderresolution',
            name='status',
            field=models.CharField(choices=[('OK', 'Succeeded'), ('ErrIllegalMove', 'Illegal move'), ('ErrIllegalDestination', 'Illegal destination'), ('ErrBounce', 'Bounced'), ('ErrInvalidSupporteeOrder', 'Invalid support order'), ('ErrIllegalSupportDestination', 'Illegal support destination'), ('ErrInvalidDestination', 'Invalid destination'), ('ErrMissingSupportUnit', 'Missing support unit')], max_length=30),
        ),
    ]
