# Generated by Django 4.2.24 on 2025-09-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_orderresolution_status'),
        ('order', '0003_copy_order_data'),  # Ensure data has been copied
    ]

    operations = [
        # Drop the old Order and OrderResolution tables
        migrations.RunSQL(
            "DROP TABLE IF EXISTS game_orderresolution CASCADE;",
            reverse_sql="-- Cannot reverse table drop, data was migrated to order app"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS game_order CASCADE;",
            reverse_sql="-- Cannot reverse table drop, data was migrated to order app"
        ),
    ]
