# Generated by Django 4.2.24 on 2025-09-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_drop_old_order_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
