# Generated by Django 4.2.24 on 2025-09-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_copy_variant_data'),
        ('game', '0012_remove_orderresolution_order_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='variant.variant'),
        ),
    ]
