# Generated by Django 4.2.24 on 2025-09-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0004_add_italy_vs_germany_variant'),
        ('game', '0013_update_variant_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='variant.variant'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='game.game'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('template', 'Template')], default='pending', max_length=20),
        ),
    ]
