# Generated by Django 4.2.24 on 2025-09-24 08:21

from django.db import migrations


def backfill_phase_variants(apps, schema_editor):
    """Backfill variant field for existing game phases."""
    Phase = apps.get_model('game', 'Phase')

    # Update all game phases (not template phases) to have their variant populated
    for phase in Phase.objects.filter(game__isnull=False, variant__isnull=True):
        phase.variant = phase.game.variant
        phase.save()


def reverse_backfill_phase_variants(apps, schema_editor):
    """Remove variant field from game phases (keep only for template phases)."""
    Phase = apps.get_model('game', 'Phase')

    # Clear variant field for all game phases
    Phase.objects.filter(game__isnull=False).update(variant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_add_variant_to_phase'),
    ]

    operations = [
        migrations.RunPython(
            backfill_phase_variants,
            reverse_backfill_phase_variants,
        ),
    ]