# Generated by Django 6.0.6 on 2026-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_game_game_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="min_reliability",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("reliable_and_new", "Reliable + New Players"),
                    ("reliable_only", "Reliable only"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
