# Generated by Django 6.0.6 on 2026-06-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_game_min_reliability"),
        ("member", "0007_member_seeking_replacement_replaced_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="managing_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managing_games",
                to="member.member",
            ),
        ),
    ]
