# Generated by Django 6.0.7 on 2026-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_backfill_game_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="commitment_requirement",
            field=models.CharField(
                choices=[("open", "Open"), ("committed", "Committed")], default="open", max_length=20
            ),
        ),
    ]
