# Generated by Django 6.1 on 2026-08-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_backfill_commitment_requirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="nation_assignment",
        ),
    ]
