# Generated by Django 6.1 on 2026-08-23 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_backfill_commitment_requirement"),
        ("variant", "0024_widen_variant_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="muster_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="muster_job_id",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="muster_reminder_job_id",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="muster_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("mustering", "Mustering"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["muster_deadline"], name="game_game_muster__ffa9b6_idx"),
        ),
    ]
