# Generated by Django 6.1 on 2026-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_remove_game_nation_assignment"),
        ("game", "0025_backfill_muster_required"),
    ]

    operations = []
