# Generated by Django 6.0.7 on 2026-07-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_profile", "0002_seed_roster"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="kind",
            field=models.CharField(choices=[("llm", "LLM"), ("dumbbot", "DumbBot")], default="llm", max_length=20),
        ),
    ]
