# Generated by Django 4.2.27 on 2026-01-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phase', '0009_revert_year_season_fix'),
        ('game', '0004_game_sandbox_alter_game_movement_phase_duration'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_draw_proposals', to='member.member')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_proposals', to='game.game')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_proposals', to='phase.phase')),
            ],
        ),
        migrations.CreateModel(
            name='DrawVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included', models.BooleanField()),
                ('accepted', models.BooleanField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_votes', to='member.member')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='draw_proposal.drawproposal')),
            ],
            options={
                'indexes': [models.Index(fields=['proposal'], name='draw_propos_proposa_8aa203_idx'), models.Index(fields=['member'], name='draw_propos_member__f158b5_idx')],
                'unique_together': {('proposal', 'member')},
            },
        ),
        migrations.AddIndex(
            model_name='drawproposal',
            index=models.Index(fields=['game'], name='draw_propos_game_id_554fee_idx'),
        ),
        migrations.AddIndex(
            model_name='drawproposal',
            index=models.Index(fields=['phase'], name='draw_propos_phase_i_4760db_idx'),
        ),
        migrations.AddIndex(
            model_name='drawproposal',
            index=models.Index(fields=['created_by'], name='draw_propos_created_027c29_idx'),
        ),
    ]
