# Generated by Django 4.2.24 on 2025-09-24 15:35

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0003_add_italy_vs_germany_template_phase"),
        ("province", "0003_add_italy_vs_germany_provinces"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Move", "Move"),
                            ("Hold", "Hold"),
                            ("Support", "Support"),
                            ("Convoy", "Convoy"),
                            ("Build", "Build"),
                            ("Disband", "Disband"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        blank=True, choices=[("Army", "Army"), ("Fleet", "Fleet")], max_length=50, null=True
                    ),
                ),
                (
                    "aux",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aux_orders",
                        to="province.province",
                    ),
                ),
                (
                    "phase_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="game.phasestate"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_orders",
                        to="province.province",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_orders",
                        to="province.province",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderResolution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Succeeded"),
                            ("ErrIllegalMove", "Illegal move"),
                            ("ErrIllegalDestination", "Illegal destination"),
                            ("ErrBounce", "Bounced"),
                            ("ErrInvalidSupporteeOrder", "Invalid support order"),
                            ("ErrIllegalSupportDestination", "Illegal support destination"),
                            ("ErrInvalidDestination", "Invalid destination"),
                            ("ErrMissingSupportUnit", "Missing support unit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_resolutions",
                        to="province.province",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resolution", to="order.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
