# Generated by Django 4.2.24 on 2025-09-20 17:42

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0010_alter_orderresolution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('Move', 'Move'), ('Hold', 'Hold'), ('Support', 'Support'), ('Convoy', 'Convoy'), ('Build', 'Build'), ('Disband', 'Disband')], max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('aux', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('Army', 'Army'), ('Fleet', 'Fleet')], max_length=50, null=True)),
                ('phase_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordersreverse', to='game.phasestate')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, order.models.ProvinceDisplayMixin),
        ),
        migrations.CreateModel(
            name='OrderResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OK', 'Succeeded'), ('ErrIllegalMove', 'Illegal move'), ('ErrIllegalDestination', 'Illegal destination'), ('ErrBounce', 'Bounced'), ('ErrInvalidSupporteeOrder', 'Invalid support order'), ('ErrIllegalSupportDestination', 'Illegal support destination'), ('ErrInvalidDestination', 'Invalid destination'), ('ErrMissingSupportUnit', 'Missing support unit')], max_length=30)),
                ('by', models.CharField(blank=True, help_text='Province that caused the resolution status (e.g. province that caused a bounce)', max_length=50, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
