# Generated by Django 4.2.24 on 2025-09-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Move', 'Move'), ('Hold', 'Hold'), ('Support', 'Support'), ('Convoy', 'Convoy'), ('Build', 'Build'), ('Disband', 'Disband')], max_length=50, null=True),
        ),
    ]
