# Generated by Django 4.2.24 on 2025-09-22 14:01

from django.db import migrations


def copy_order_data(apps, schema_editor):
    """
    Copy all data from game.Order to order.Order and game.OrderResolution to order.OrderResolution
    """
    # Get model references
    GameOrder = apps.get_model('game', 'Order')
    GameOrderResolution = apps.get_model('game', 'OrderResolution')
    OrderOrder = apps.get_model('order', 'Order')
    OrderOrderResolution = apps.get_model('order', 'OrderResolution')

    # Copy Order data
    for old_order in GameOrder.objects.all():
        # Create new order with same ID and data
        new_order = OrderOrder.objects.create(
            id=old_order.id,
            created_at=old_order.created_at,
            updated_at=old_order.updated_at,
            phase_state=old_order.phase_state,
            order_type=old_order.order_type,
            source=old_order.source,
            target=old_order.target,
            aux=old_order.aux,
            unit_type=old_order.unit_type,
        )
        print(f"Copied Order {old_order.id}: {old_order.source} -> {old_order.target}")

    # Copy OrderResolution data
    for old_resolution in GameOrderResolution.objects.all():
        # Get the corresponding new order
        new_order = OrderOrder.objects.get(id=old_resolution.order.id)

        # Create new resolution
        new_resolution = OrderOrderResolution.objects.create(
            id=old_resolution.id,
            created_at=old_resolution.created_at,
            updated_at=old_resolution.updated_at,
            order=new_order,
            status=old_resolution.status,
            by=old_resolution.by,
        )
        print(f"Copied OrderResolution {old_resolution.id}: {old_resolution.status}")


def reverse_copy_order_data(apps, schema_editor):
    """
    Reverse migration - delete all data from order.Order and order.OrderResolution
    """
    OrderOrder = apps.get_model('order', 'Order')
    OrderOrderResolution = apps.get_model('order', 'OrderResolution')

    OrderOrderResolution.objects.all().delete()
    OrderOrder.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_type'),
        ('game', '0010_alter_orderresolution_status'),  # Make sure game migrations are applied
    ]

    operations = [
        migrations.RunPython(copy_order_data, reverse_copy_order_data),
    ]
