# Generated by Django 4.2.24 on 2025-09-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_drop_old_order_tables'),
        ('order', '0003_copy_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phase_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='game.phasestate'),
        ),
    ]
