# Generated by Django 4.2.30 on 2026-05-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderresolution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_implicit',
            field=models.BooleanField(default=False),
        ),
    ]
