# Generated by Django 4.2.30 on 2026-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderresolution_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='is_implicit',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        ),
    ]
