# Generated by Django 6.0.8 on 2026-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_add_is_implicit_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderresolution",
            name="status",
            field=models.CharField(
                choices=[
                    ("OK", "Succeeded"),
                    ("ErrIllegalMove", "Illegal move"),
                    ("ErrIllegalDestination", "Illegal destination"),
                    ("ErrBounce", "Bounced"),
                    ("ErrInvalidSupporteeOrder", "Invalid support order"),
                    ("ErrIllegalSupportDestination", "Illegal support destination"),
                    ("ErrInvalidDestination", "Invalid destination"),
                    ("ErrMissingSupportUnit", "Missing support unit"),
                    ("ErrMissingUnit", "Missing unit"),
                    ("ErrSupportBroken", "Support broken"),
                    ("ErrMissingConvoyPath", "Missing convoy path"),
                    ("ErrConvoyDislodged", "Convoy dislodged"),
                ],
                max_length=30,
            ),
        ),
    ]
