# Generated by Django 4.2.24 on 2025-09-24 12:52

from django.db import migrations


def populate_provinces(apps, schema_editor):
    """Populate Province model with data from Variant.provinces_data."""
    Variant = apps.get_model('variant', 'Variant')
    Province = apps.get_model('province', 'Province')

    for variant in Variant.objects.all():
        if variant.provinces_data:
            for province_data in variant.provinces_data:
                Province.objects.get_or_create(
                    province_id=province_data['id'],
                    variant=variant,
                    defaults={
                        'name': province_data['name'],
                        'type': province_data['type'],
                        'supply_center': province_data['supply_center'],
                    }
                )


def reverse_populate_provinces(apps, schema_editor):
    """Remove all Province records."""
    Province = apps.get_model('province', 'Province')
    Province.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
        ('variant', '0006_remove_start_data'),
    ]

    operations = [
        migrations.RunPython(
            populate_provinces,
            reverse_populate_provinces,
        ),
    ]
