# Generated by Django 4.2.24 on 2025-09-24 14:34

from django.db import migrations


def add_italy_vs_germany_provinces(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the Italy vs Germany variant and classical variant
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    classical_variant = Variant.objects.get(id="classical")

    # Copy all provinces from classical to Italy vs Germany (same map)
    classical_provinces = Province.objects.filter(variant=classical_variant)

    for classical_province in classical_provinces:
        Province.objects.create(
            province_id=classical_province.province_id,
            name=classical_province.name,
            type=classical_province.type,
            supply_center=classical_province.supply_center,
            variant=italy_germany_variant,
        )


def remove_italy_vs_germany_provinces(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    Province.objects.filter(variant=italy_germany_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0002_add_classical_provinces"),
        ("variant", "0003_add_italy_vs_germany_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_provinces,
            remove_italy_vs_germany_provinces,
        ),
    ]
