# Generated by Django 4.2.24 on 2025-09-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0006_remove_start_data'),
        ('province', '0002_populate_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_set', to='variant.variant'),
        ),
    ]
