# Generated by Django 4.2.24 on 2025-09-28 13:13

from django.db import migrations


def set_named_coasts_type(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the classical variant
    classical_variant = Variant.objects.get(id="classical")

    # Named coast province IDs to update
    named_coast_ids = ["bul/ec", "bul/sc", "spa/nc", "spa/sc", "stp/sc", "stp/nc"]

    # Update the type to 'named_coast' for these provinces in the classical variant only
    Province.objects.filter(province_id__in=named_coast_ids, variant=classical_variant).update(type="named_coast")


def reverse_set_named_coasts_type(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the classical variant
    classical_variant = Variant.objects.get(id="classical")

    # Named coast province IDs to revert
    named_coast_ids = ["bul/ec", "bul/sc", "spa/nc", "spa/sc", "stp/sc", "stp/nc"]

    # Revert the type back to 'sea' for these provinces in the classical variant only
    Province.objects.filter(province_id__in=named_coast_ids, variant=classical_variant).update(type="sea")


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0004_alter_province_type"),
    ]

    operations = [
        migrations.RunPython(
            set_named_coasts_type,
            reverse_set_named_coasts_type,
        ),
    ]
