# Generated by Django 4.2.24 on 2025-09-28 13:16

from django.db import migrations


def set_named_coasts_type(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the Italy vs Germany variant
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")

    # Named coast province IDs to update
    named_coast_ids = ["bul/ec", "bul/sc", "spa/nc", "spa/sc", "stp/sc", "stp/nc"]

    # Update the type to 'named_coast' for these provinces in the Italy vs Germany variant only
    Province.objects.filter(province_id__in=named_coast_ids, variant=italy_germany_variant).update(type="named_coast")


def reverse_set_named_coasts_type(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the Italy vs Germany variant
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")

    # Named coast province IDs to revert
    named_coast_ids = ["bul/ec", "bul/sc", "spa/nc", "spa/sc", "stp/sc", "stp/nc"]

    # Revert the type back to 'sea' for these provinces in the Italy vs Germany variant only
    Province.objects.filter(province_id__in=named_coast_ids, variant=italy_germany_variant).update(type="sea")


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0005_set_named_coasts_classical"),
    ]

    operations = [
        migrations.RunPython(
            set_named_coasts_type,
            reverse_set_named_coasts_type,
        ),
    ]
