# Generated by Django 4.2.24 on 2025-09-28 13:52

from django.db import migrations


def set_named_coast_parents_italy_vs_germany(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the Italy vs Germany variant
    italy_vs_germany_variant = Variant.objects.get(id="italy-vs-germany")

    # Define named coast to parent mappings (same as classical)
    named_coast_mappings = {
        "spa/nc": "spa",
        "spa/sc": "spa",
        "bul/ec": "bul",
        "bul/sc": "bul",
        "stp/nc": "stp",
        "stp/sc": "stp",
    }

    # Set parent relationships for named coasts
    for named_coast_id, parent_id in named_coast_mappings.items():
        try:
            named_coast = Province.objects.get(
                province_id=named_coast_id,
                variant=italy_vs_germany_variant
            )
            parent = Province.objects.get(
                province_id=parent_id,
                variant=italy_vs_germany_variant
            )
            named_coast.parent = parent
            named_coast.save()
        except Province.DoesNotExist:
            # Skip if province doesn't exist
            pass


def reverse_set_named_coast_parents_italy_vs_germany(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    try:
        italy_vs_germany_variant = Variant.objects.get(id="italy-vs-germany")
        # Clear all parent relationships for named coasts in Italy vs Germany
        named_coast_ids = ["spa/nc", "spa/sc", "bul/ec", "bul/sc", "stp/nc", "stp/sc"]
        Province.objects.filter(
            province_id__in=named_coast_ids,
            variant=italy_vs_germany_variant
        ).update(parent=None)
    except Variant.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0008_set_named_coast_parents_classical'),
    ]

    operations = [
        migrations.RunPython(
            set_named_coast_parents_italy_vs_germany,
            reverse_set_named_coast_parents_italy_vs_germany,
        ),
    ]
