# Backfills Province.adjacencies for youngstown-redux, vietnam-war and canton.
#
# Adjacency data was extracted from the godip Go library. Each province's
# adjacencies are stored as a list of {"to", "pass"} entries. The migration
# verifies that every edge is mirrored on its other endpoint before writing;
# an asymmetric edge aborts the migration.

from django.db import migrations


ADJACENCIES = {
    "youngstown-redux": {
        "ade": [{"to": "ara", "pass": "army"}, {"to": "ara/sc", "pass": "fleet"}, {"to": "goa", "pass": "fleet"}, {"to": "red", "pass": "fleet"}, {"to": "yem", "pass": "both"}],
        "adr": [{"to": "alb", "pass": "fleet"}, {"to": "apu", "pass": "fleet"}, {"to": "ion", "pass": "fleet"}, {"to": "sar", "pass": "fleet"}, {"to": "tes", "pass": "fleet"}, {"to": "ven", "pass": "fleet"}],
        "aeg": [{"to": "con", "pass": "fleet"}, {"to": "ems", "pass": "fleet"}, {"to": "gre", "pass": "fleet"}, {"to": "ion", "pass": "fleet"}, {"to": "kon", "pass": "fleet"}, {"to": "mac", "pass": "fleet"}],
        "afg": [{"to": "kas", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sid", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "aki": [{"to": "kyo", "pass": "both"}, {"to": "npo", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "tok", "pass": "both"}],
        "alb": [{"to": "adr", "pass": "fleet"}, {"to": "gre", "pass": "both"}, {"to": "ion", "pass": "fleet"}, {"to": "mac", "pass": "army"}, {"to": "sar", "pass": "both"}, {"to": "ser", "pass": "army"}],
        "alg": [{"to": "mor", "pass": "both"}, {"to": "sah", "pass": "army"}, {"to": "tun", "pass": "both"}, {"to": "tyh", "pass": "fleet"}, {"to": "wms", "pass": "fleet"}],
        "and": [{"to": "bay", "pass": "fleet"}, {"to": "bum", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "sig", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}, {"to": "tha/wc", "pass": "fleet"}],
        "ank": [{"to": "arm", "pass": "both"}, {"to": "bla", "pass": "fleet"}, {"to": "con", "pass": "both"}, {"to": "kon", "pass": "army"}],
        "ann": [{"to": "cam", "pass": "army"}, {"to": "goo", "pass": "fleet"}, {"to": "lao", "pass": "army"}, {"to": "sai", "pass": "both"}, {"to": "scs", "pass": "fleet"}, {"to": "vit", "pass": "both"}],
        "apu": [{"to": "adr", "pass": "fleet"}, {"to": "ion", "pass": "fleet"}, {"to": "nap", "pass": "both"}, {"to": "rom", "pass": "army"}, {"to": "ven", "pass": "both"}],
        "ara": [{"to": "ade", "pass": "army"}, {"to": "bag", "pass": "army"}, {"to": "lev", "pass": "army"}, {"to": "mec", "pass": "army"}, {"to": "oma", "pass": "army"}, {"to": "yem", "pass": "army"}],
        "ara/nc": [{"to": "bag", "pass": "fleet"}, {"to": "oma", "pass": "fleet"}, {"to": "psg", "pass": "fleet"}],
        "ara/sc": [{"to": "ade", "pass": "fleet"}, {"to": "mec", "pass": "fleet"}, {"to": "red", "pass": "fleet"}],
        "arm": [{"to": "ank", "pass": "both"}, {"to": "bag", "pass": "army"}, {"to": "bla", "pass": "fleet"}, {"to": "cau", "pass": "army"}, {"to": "kon", "pass": "army"}, {"to": "lev", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sev", "pass": "both"}],
        "ars": [{"to": "bom", "pass": "fleet"}, {"to": "goa", "pass": "fleet"}, {"to": "oma", "pass": "fleet"}, {"to": "per", "pass": "fleet"}, {"to": "psg", "pass": "fleet"}, {"to": "sid", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}, {"to": "yem", "pass": "fleet"}],
        "awd": [{"to": "eth", "pass": "both"}, {"to": "goa", "pass": "fleet"}, {"to": "mog", "pass": "both"}],
        "bag": [{"to": "ara", "pass": "army"}, {"to": "ara/nc", "pass": "fleet"}, {"to": "arm", "pass": "army"}, {"to": "lev", "pass": "army"}, {"to": "per", "pass": "both"}, {"to": "psg", "pass": "fleet"}],
        "bal": [{"to": "ber", "pass": "fleet"}, {"to": "den", "pass": "fleet"}, {"to": "gob", "pass": "fleet"}, {"to": "kie", "pass": "fleet"}, {"to": "lia", "pass": "fleet"}, {"to": "pru", "pass": "fleet"}, {"to": "swe", "pass": "fleet"}],
        "bar": [{"to": "nay", "pass": "fleet"}, {"to": "noi", "pass": "fleet"}, {"to": "stp/nc", "pass": "fleet"}],
        "bay": [{"to": "and", "pass": "fleet"}, {"to": "bum", "pass": "fleet"}, {"to": "cal", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "mad", "pass": "fleet"}],
        "bel": [{"to": "bug", "pass": "army"}, {"to": "col", "pass": "army"}, {"to": "eng", "pass": "fleet"}, {"to": "hol", "pass": "both"}, {"to": "not", "pass": "fleet"}, {"to": "pic", "pass": "both"}],
        "ber": [{"to": "bal", "pass": "fleet"}, {"to": "kie", "pass": "both"}, {"to": "pru", "pass": "both"}, {"to": "sax", "pass": "army"}, {"to": "sil", "pass": "army"}],
        "bla": [{"to": "ank", "pass": "fleet"}, {"to": "arm", "pass": "fleet"}, {"to": "bul", "pass": "fleet"}, {"to": "con", "pass": "fleet"}, {"to": "rum", "pass": "fleet"}, {"to": "sev", "pass": "fleet"}],
        "boh": [{"to": "gal", "pass": "army"}, {"to": "mun", "pass": "army"}, {"to": "sax", "pass": "army"}, {"to": "sil", "pass": "army"}, {"to": "tyo", "pass": "army"}, {"to": "vnn", "pass": "army"}],
        "bom": [{"to": "ars", "pass": "fleet"}, {"to": "dec", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "mad", "pass": "both"}, {"to": "sid", "pass": "both"}, {"to": "wio", "pass": "fleet"}],
        "bor": [{"to": "cel", "pass": "fleet"}, {"to": "guh", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "bre": [{"to": "eng", "pass": "fleet"}, {"to": "gas", "pass": "both"}, {"to": "mid", "pass": "fleet"}, {"to": "par", "pass": "army"}, {"to": "pic", "pass": "both"}],
        "bud": [{"to": "gal", "pass": "army"}, {"to": "rum", "pass": "army"}, {"to": "sar", "pass": "army"}, {"to": "ser", "pass": "army"}, {"to": "tes", "pass": "army"}, {"to": "vnn", "pass": "army"}],
        "bug": [{"to": "bel", "pass": "army"}, {"to": "col", "pass": "army"}, {"to": "gas", "pass": "army"}, {"to": "mar", "pass": "army"}, {"to": "par", "pass": "army"}, {"to": "pic", "pass": "army"}, {"to": "swa", "pass": "army"}, {"to": "swi", "pass": "army"}],
        "bul": [{"to": "bla", "pass": "fleet"}, {"to": "con", "pass": "both"}, {"to": "mac", "pass": "army"}, {"to": "rum", "pass": "both"}, {"to": "ser", "pass": "army"}],
        "bum": [{"to": "and", "pass": "fleet"}, {"to": "bay", "pass": "fleet"}, {"to": "cal", "pass": "both"}, {"to": "lao", "pass": "army"}, {"to": "tha", "pass": "army"}, {"to": "tha/wc", "pass": "fleet"}, {"to": "tib", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "bxa": [{"to": "bxb", "pass": "fleet"}, {"to": "bxc", "pass": "fleet"}, {"to": "bxd", "pass": "fleet"}, {"to": "nao", "pass": "fleet"}],
        "bxb": [{"to": "bxa", "pass": "fleet"}, {"to": "bxc", "pass": "fleet"}, {"to": "bxe", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}],
        "bxc": [{"to": "bxa", "pass": "fleet"}, {"to": "bxb", "pass": "fleet"}, {"to": "bxf", "pass": "fleet"}, {"to": "bxg", "pass": "fleet"}, {"to": "bxh", "pass": "fleet"}, {"to": "sao", "pass": "fleet"}],
        "bxd": [{"to": "bxa", "pass": "fleet"}, {"to": "bxe", "pass": "fleet"}, {"to": "bxf", "pass": "fleet"}, {"to": "npo", "pass": "fleet"}],
        "bxe": [{"to": "bxb", "pass": "fleet"}, {"to": "bxd", "pass": "fleet"}, {"to": "bxf", "pass": "fleet"}, {"to": "spo", "pass": "fleet"}],
        "bxf": [{"to": "bxc", "pass": "fleet"}, {"to": "bxd", "pass": "fleet"}, {"to": "bxe", "pass": "fleet"}, {"to": "bxg", "pass": "fleet"}, {"to": "bxh", "pass": "fleet"}, {"to": "tim", "pass": "fleet"}],
        "bxg": [{"to": "bxc", "pass": "fleet"}, {"to": "bxf", "pass": "fleet"}, {"to": "bxh", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "bxh": [{"to": "bxc", "pass": "fleet"}, {"to": "bxf", "pass": "fleet"}, {"to": "bxg", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}],
        "cal": [{"to": "bay", "pass": "fleet"}, {"to": "bum", "pass": "both"}, {"to": "dec", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "mad", "pass": "both"}, {"to": "nep", "pass": "army"}, {"to": "tib", "pass": "army"}],
        "cam": [{"to": "ann", "pass": "army"}, {"to": "guh", "pass": "fleet"}, {"to": "lao", "pass": "army"}, {"to": "sai", "pass": "both"}, {"to": "tha", "pass": "army"}, {"to": "tha/ec", "pass": "fleet"}],
        "cau": [{"to": "arm", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "oms", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sev", "pass": "army"}],
        "cel": [{"to": "bor", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "spo", "pass": "fleet"}, {"to": "tim", "pass": "fleet"}],
        "cen": [{"to": "fez", "pass": "army"}, {"to": "sah", "pass": "army"}, {"to": "sud", "pass": "army"}],
        "cey": [{"to": "eio", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "cly": [{"to": "edi", "pass": "both"}, {"to": "lie", "pass": "both"}, {"to": "nao", "pass": "fleet"}, {"to": "noi", "pass": "fleet"}],
        "col": [{"to": "bel", "pass": "army"}, {"to": "bug", "pass": "army"}, {"to": "hol", "pass": "army"}, {"to": "kie", "pass": "army"}, {"to": "mun", "pass": "army"}, {"to": "sax", "pass": "army"}, {"to": "swa", "pass": "army"}],
        "con": [{"to": "aeg", "pass": "fleet"}, {"to": "ank", "pass": "both"}, {"to": "bla", "pass": "fleet"}, {"to": "bul", "pass": "both"}, {"to": "kon", "pass": "both"}, {"to": "mac", "pass": "both"}],
        "cyr": [{"to": "egy", "pass": "both"}, {"to": "ems", "pass": "fleet"}, {"to": "fez", "pass": "army"}, {"to": "ion", "pass": "fleet"}, {"to": "trp", "pass": "both"}],
        "dec": [{"to": "bom", "pass": "army"}, {"to": "cal", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "mad", "pass": "army"}],
        "del": [{"to": "bom", "pass": "army"}, {"to": "cal", "pass": "army"}, {"to": "dec", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "nep", "pass": "army"}, {"to": "sid", "pass": "army"}, {"to": "tib", "pass": "army"}],
        "den": [{"to": "bal", "pass": "fleet"}, {"to": "hel", "pass": "fleet"}, {"to": "kie", "pass": "both"}, {"to": "not", "pass": "fleet"}, {"to": "ska", "pass": "fleet"}, {"to": "swe", "pass": "both"}],
        "ecs": [{"to": "for", "pass": "fleet"}, {"to": "heb/sc", "pass": "fleet"}, {"to": "kag", "pass": "fleet"}, {"to": "kor", "pass": "fleet"}, {"to": "osa", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "sha", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "spo", "pass": "fleet"}, {"to": "tsi", "pass": "fleet"}, {"to": "yel", "pass": "fleet"}],
        "edi": [{"to": "cly", "pass": "both"}, {"to": "lie", "pass": "army"}, {"to": "noi", "pass": "fleet"}, {"to": "not", "pass": "fleet"}, {"to": "yor", "pass": "both"}],
        "egy": [{"to": "cyr", "pass": "both"}, {"to": "ems", "pass": "fleet"}, {"to": "fez", "pass": "army"}, {"to": "lev", "pass": "army"}, {"to": "lev/nc", "pass": "fleet"}, {"to": "lev/sc", "pass": "fleet"}, {"to": "red", "pass": "fleet"}, {"to": "sud", "pass": "both"}],
        "eio": [{"to": "and", "pass": "fleet"}, {"to": "bay", "pass": "fleet"}, {"to": "bxh", "pass": "fleet"}, {"to": "cey", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "mad", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}, {"to": "tim", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "ems": [{"to": "aeg", "pass": "fleet"}, {"to": "cyr", "pass": "fleet"}, {"to": "egy", "pass": "fleet"}, {"to": "ion", "pass": "fleet"}, {"to": "kon", "pass": "fleet"}, {"to": "lev/nc", "pass": "fleet"}],
        "eng": [{"to": "bel", "pass": "fleet"}, {"to": "bre", "pass": "fleet"}, {"to": "iri", "pass": "fleet"}, {"to": "lon", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "not", "pass": "fleet"}, {"to": "pic", "pass": "fleet"}, {"to": "wal", "pass": "fleet"}],
        "eth": [{"to": "awd", "pass": "both"}, {"to": "goa", "pass": "fleet"}, {"to": "ken", "pass": "army"}, {"to": "mog", "pass": "army"}, {"to": "red", "pass": "fleet"}, {"to": "sud", "pass": "both"}],
        "fez": [{"to": "cen", "pass": "army"}, {"to": "cyr", "pass": "army"}, {"to": "egy", "pass": "army"}, {"to": "sah", "pass": "army"}, {"to": "sud", "pass": "army"}, {"to": "trp", "pass": "army"}],
        "fin": [{"to": "gob", "pass": "fleet"}, {"to": "nay", "pass": "army"}, {"to": "stp", "pass": "army"}, {"to": "stp/sc", "pass": "fleet"}, {"to": "swe", "pass": "both"}],
        "for": [{"to": "ecs", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "gal": [{"to": "boh", "pass": "army"}, {"to": "bud", "pass": "army"}, {"to": "rum", "pass": "army"}, {"to": "sil", "pass": "army"}, {"to": "ukr", "pass": "army"}, {"to": "vnn", "pass": "army"}, {"to": "war", "pass": "army"}],
        "gas": [{"to": "bre", "pass": "both"}, {"to": "bug", "pass": "army"}, {"to": "mar", "pass": "army"}, {"to": "mid", "pass": "fleet"}, {"to": "par", "pass": "army"}, {"to": "spa", "pass": "army"}, {"to": "spa/nc", "pass": "fleet"}],
        "goa": [{"to": "ade", "pass": "fleet"}, {"to": "ars", "pass": "fleet"}, {"to": "awd", "pass": "fleet"}, {"to": "eth", "pass": "fleet"}, {"to": "hor", "pass": "fleet"}, {"to": "mog", "pass": "fleet"}, {"to": "red", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}, {"to": "yem", "pass": "fleet"}],
        "gob": [{"to": "bal", "pass": "fleet"}, {"to": "fin", "pass": "fleet"}, {"to": "lia", "pass": "fleet"}, {"to": "stp/sc", "pass": "fleet"}, {"to": "swe", "pass": "fleet"}],
        "gol": [{"to": "mar", "pass": "fleet"}, {"to": "pie", "pass": "fleet"}, {"to": "rom", "pass": "fleet"}, {"to": "spa/sc", "pass": "fleet"}, {"to": "tyh", "pass": "fleet"}, {"to": "wms", "pass": "fleet"}],
        "goo": [{"to": "ann", "pass": "fleet"}, {"to": "gua", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "vit", "pass": "fleet"}],
        "gre": [{"to": "aeg", "pass": "fleet"}, {"to": "alb", "pass": "both"}, {"to": "ion", "pass": "fleet"}, {"to": "mac", "pass": "both"}],
        "gua": [{"to": "goo", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "sha", "pass": "both"}, {"to": "vit", "pass": "both"}, {"to": "wuh", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "guh": [{"to": "bor", "pass": "fleet"}, {"to": "cam", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "sai", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "sig", "pass": "fleet"}, {"to": "tha/ec", "pass": "fleet"}],
        "heb": [{"to": "pek", "pass": "army"}, {"to": "qin", "pass": "army"}, {"to": "sha", "pass": "army"}, {"to": "tsi", "pass": "army"}, {"to": "wuh", "pass": "army"}],
        "heb/nc": [{"to": "pek", "pass": "fleet"}, {"to": "tsi", "pass": "fleet"}, {"to": "yel", "pass": "fleet"}],
        "heb/sc": [{"to": "ecs", "pass": "fleet"}, {"to": "sha", "pass": "fleet"}, {"to": "tsi", "pass": "fleet"}],
        "hel": [{"to": "den", "pass": "fleet"}, {"to": "hol", "pass": "fleet"}, {"to": "kie", "pass": "fleet"}, {"to": "not", "pass": "fleet"}],
        "hol": [{"to": "bel", "pass": "both"}, {"to": "col", "pass": "army"}, {"to": "hel", "pass": "fleet"}, {"to": "kie", "pass": "both"}, {"to": "not", "pass": "fleet"}],
        "hor": [{"to": "goa", "pass": "fleet"}, {"to": "ken", "pass": "fleet"}, {"to": "mog", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "inn": [{"to": "man", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "pek", "pass": "army"}, {"to": "qin", "pass": "army"}, {"to": "xin", "pass": "army"}],
        "ion": [{"to": "adr", "pass": "fleet"}, {"to": "aeg", "pass": "fleet"}, {"to": "alb", "pass": "fleet"}, {"to": "apu", "pass": "fleet"}, {"to": "cyr", "pass": "fleet"}, {"to": "ems", "pass": "fleet"}, {"to": "gre", "pass": "fleet"}, {"to": "nap", "pass": "fleet"}, {"to": "trp", "pass": "fleet"}, {"to": "tun", "pass": "fleet"}, {"to": "tyh", "pass": "fleet"}],
        "ire": [{"to": "iri", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "nao", "pass": "fleet"}],
        "iri": [{"to": "eng", "pass": "fleet"}, {"to": "ire", "pass": "fleet"}, {"to": "lie", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "nao", "pass": "fleet"}, {"to": "wal", "pass": "fleet"}],
        "jav": [{"to": "cel", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "tim", "pass": "fleet"}],
        "jvs": [{"to": "and", "pass": "fleet"}, {"to": "bor", "pass": "fleet"}, {"to": "cel", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "guh", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "sig", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}],
        "kag": [{"to": "ecs", "pass": "fleet"}, {"to": "kyo", "pass": "both"}, {"to": "osa", "pass": "both"}, {"to": "soj", "pass": "fleet"}],
        "kam": [{"to": "npo", "pass": "fleet"}, {"to": "sib", "pass": "army"}, {"to": "soo", "pass": "fleet"}, {"to": "vla", "pass": "both"}],
        "kar": [{"to": "npo", "pass": "fleet"}, {"to": "sak", "pass": "both"}, {"to": "soj", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}],
        "kas": [{"to": "afg", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "sid", "pass": "army"}, {"to": "tib", "pass": "army"}],
        "ken": [{"to": "eth", "pass": "army"}, {"to": "hor", "pass": "fleet"}, {"to": "mog", "pass": "both"}, {"to": "sud", "pass": "army"}],
        "kie": [{"to": "bal", "pass": "fleet"}, {"to": "ber", "pass": "both"}, {"to": "col", "pass": "army"}, {"to": "den", "pass": "both"}, {"to": "hel", "pass": "fleet"}, {"to": "hol", "pass": "both"}, {"to": "sax", "pass": "army"}],
        "kon": [{"to": "aeg", "pass": "fleet"}, {"to": "ank", "pass": "army"}, {"to": "arm", "pass": "army"}, {"to": "con", "pass": "both"}, {"to": "ems", "pass": "fleet"}, {"to": "lev", "pass": "army"}, {"to": "lev/nc", "pass": "fleet"}],
        "kor": [{"to": "ecs", "pass": "fleet"}, {"to": "man", "pass": "both"}, {"to": "soj", "pass": "fleet"}, {"to": "vla", "pass": "both"}, {"to": "yel", "pass": "fleet"}],
        "kyo": [{"to": "aki", "pass": "both"}, {"to": "kag", "pass": "both"}, {"to": "osa", "pass": "army"}, {"to": "shi", "pass": "army"}, {"to": "soj", "pass": "fleet"}, {"to": "tok", "pass": "army"}],
        "lao": [{"to": "ann", "pass": "army"}, {"to": "bum", "pass": "army"}, {"to": "cam", "pass": "army"}, {"to": "tha", "pass": "army"}, {"to": "vit", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "lev": [{"to": "ara", "pass": "army"}, {"to": "arm", "pass": "army"}, {"to": "bag", "pass": "army"}, {"to": "egy", "pass": "army"}, {"to": "kon", "pass": "army"}, {"to": "mec", "pass": "army"}],
        "lev/nc": [{"to": "egy", "pass": "fleet"}, {"to": "ems", "pass": "fleet"}, {"to": "kon", "pass": "fleet"}],
        "lev/sc": [{"to": "egy", "pass": "fleet"}, {"to": "mec", "pass": "fleet"}, {"to": "red", "pass": "fleet"}],
        "lia": [{"to": "bal", "pass": "fleet"}, {"to": "gob", "pass": "fleet"}, {"to": "mos", "pass": "army"}, {"to": "pru", "pass": "both"}, {"to": "stp", "pass": "army"}, {"to": "stp/sc", "pass": "fleet"}, {"to": "war", "pass": "army"}],
        "lie": [{"to": "cly", "pass": "both"}, {"to": "edi", "pass": "army"}, {"to": "iri", "pass": "fleet"}, {"to": "nao", "pass": "fleet"}, {"to": "wal", "pass": "both"}, {"to": "yor", "pass": "army"}],
        "lon": [{"to": "eng", "pass": "fleet"}, {"to": "not", "pass": "fleet"}, {"to": "wal", "pass": "both"}, {"to": "yor", "pass": "both"}],
        "mac": [{"to": "aeg", "pass": "fleet"}, {"to": "alb", "pass": "army"}, {"to": "bul", "pass": "army"}, {"to": "con", "pass": "both"}, {"to": "gre", "pass": "both"}, {"to": "ser", "pass": "army"}],
        "mad": [{"to": "bay", "pass": "fleet"}, {"to": "bom", "pass": "both"}, {"to": "cal", "pass": "both"}, {"to": "dec", "pass": "army"}, {"to": "eio", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "mal": [{"to": "mor", "pass": "both"}, {"to": "sah", "pass": "army"}, {"to": "sao", "pass": "fleet"}],
        "man": [{"to": "inn", "pass": "army"}, {"to": "kor", "pass": "both"}, {"to": "mon", "pass": "army"}, {"to": "pek", "pass": "both"}, {"to": "sib", "pass": "army"}, {"to": "vla", "pass": "army"}, {"to": "yel", "pass": "fleet"}],
        "mar": [{"to": "bug", "pass": "army"}, {"to": "gas", "pass": "army"}, {"to": "gol", "pass": "fleet"}, {"to": "pie", "pass": "both"}, {"to": "spa", "pass": "army"}, {"to": "spa/sc", "pass": "fleet"}, {"to": "swi", "pass": "army"}],
        "mec": [{"to": "ara", "pass": "army"}, {"to": "ara/sc", "pass": "fleet"}, {"to": "lev", "pass": "army"}, {"to": "lev/sc", "pass": "fleet"}, {"to": "red", "pass": "fleet"}],
        "mid": [{"to": "bre", "pass": "fleet"}, {"to": "bxb", "pass": "fleet"}, {"to": "eng", "pass": "fleet"}, {"to": "gas", "pass": "fleet"}, {"to": "ire", "pass": "fleet"}, {"to": "iri", "pass": "fleet"}, {"to": "mor", "pass": "fleet"}, {"to": "nao", "pass": "fleet"}, {"to": "por", "pass": "fleet"}, {"to": "sao", "pass": "fleet"}, {"to": "spa/nc", "pass": "fleet"}, {"to": "spa/sc", "pass": "fleet"}, {"to": "wms", "pass": "fleet"}],
        "mil": [{"to": "pie", "pass": "army"}, {"to": "rom", "pass": "army"}, {"to": "swi", "pass": "army"}, {"to": "tyo", "pass": "army"}, {"to": "ven", "pass": "army"}],
        "mog": [{"to": "awd", "pass": "both"}, {"to": "eth", "pass": "army"}, {"to": "goa", "pass": "fleet"}, {"to": "hor", "pass": "fleet"}, {"to": "ken", "pass": "both"}],
        "mon": [{"to": "inn", "pass": "army"}, {"to": "man", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "xin", "pass": "army"}],
        "mor": [{"to": "alg", "pass": "both"}, {"to": "mal", "pass": "both"}, {"to": "mid", "pass": "fleet"}, {"to": "sah", "pass": "army"}, {"to": "sao", "pass": "fleet"}, {"to": "wms", "pass": "fleet"}],
        "mos": [{"to": "cau", "pass": "army"}, {"to": "lia", "pass": "army"}, {"to": "oms", "pass": "army"}, {"to": "sev", "pass": "army"}, {"to": "stp", "pass": "army"}, {"to": "ukr", "pass": "army"}, {"to": "war", "pass": "army"}],
        "mun": [{"to": "boh", "pass": "army"}, {"to": "col", "pass": "army"}, {"to": "sax", "pass": "army"}, {"to": "swa", "pass": "army"}, {"to": "swi", "pass": "army"}, {"to": "tyo", "pass": "army"}],
        "nao": [{"to": "bxa", "pass": "fleet"}, {"to": "cly", "pass": "fleet"}, {"to": "ire", "pass": "fleet"}, {"to": "iri", "pass": "fleet"}, {"to": "lie", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "noi", "pass": "fleet"}],
        "nap": [{"to": "apu", "pass": "both"}, {"to": "ion", "pass": "fleet"}, {"to": "rom", "pass": "both"}, {"to": "tyh", "pass": "fleet"}],
        "nay": [{"to": "bar", "pass": "fleet"}, {"to": "fin", "pass": "army"}, {"to": "noi", "pass": "fleet"}, {"to": "not", "pass": "fleet"}, {"to": "ska", "pass": "fleet"}, {"to": "stp", "pass": "army"}, {"to": "stp/nc", "pass": "fleet"}, {"to": "swe", "pass": "both"}],
        "nep": [{"to": "cal", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "tib", "pass": "army"}],
        "noi": [{"to": "bar", "pass": "fleet"}, {"to": "cly", "pass": "fleet"}, {"to": "edi", "pass": "fleet"}, {"to": "nao", "pass": "fleet"}, {"to": "nay", "pass": "fleet"}, {"to": "not", "pass": "fleet"}],
        "not": [{"to": "bel", "pass": "fleet"}, {"to": "den", "pass": "fleet"}, {"to": "edi", "pass": "fleet"}, {"to": "eng", "pass": "fleet"}, {"to": "hel", "pass": "fleet"}, {"to": "hol", "pass": "fleet"}, {"to": "lon", "pass": "fleet"}, {"to": "nay", "pass": "fleet"}, {"to": "noi", "pass": "fleet"}, {"to": "ska", "pass": "fleet"}, {"to": "yor", "pass": "fleet"}],
        "npo": [{"to": "aki", "pass": "fleet"}, {"to": "bxd", "pass": "fleet"}, {"to": "kam", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "sap", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}, {"to": "spo", "pass": "fleet"}, {"to": "tok", "pass": "fleet"}],
        "oma": [{"to": "ara", "pass": "army"}, {"to": "ara/nc", "pass": "fleet"}, {"to": "ars", "pass": "fleet"}, {"to": "psg", "pass": "fleet"}, {"to": "yem", "pass": "both"}],
        "oms": [{"to": "cau", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "stp", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "osa": [{"to": "ecs", "pass": "fleet"}, {"to": "kag", "pass": "both"}, {"to": "kyo", "pass": "army"}, {"to": "shi", "pass": "both"}, {"to": "spo", "pass": "fleet"}],
        "par": [{"to": "bre", "pass": "army"}, {"to": "bug", "pass": "army"}, {"to": "gas", "pass": "army"}, {"to": "pic", "pass": "army"}],
        "pek": [{"to": "heb", "pass": "army"}, {"to": "heb/nc", "pass": "fleet"}, {"to": "inn", "pass": "army"}, {"to": "man", "pass": "both"}, {"to": "qin", "pass": "army"}, {"to": "yel", "pass": "fleet"}],
        "per": [{"to": "afg", "pass": "army"}, {"to": "arm", "pass": "army"}, {"to": "ars", "pass": "fleet"}, {"to": "bag", "pass": "both"}, {"to": "cau", "pass": "army"}, {"to": "psg", "pass": "fleet"}, {"to": "sid", "pass": "both"}, {"to": "tur", "pass": "army"}],
        "phi": [{"to": "cel", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "spo", "pass": "fleet"}],
        "pic": [{"to": "bel", "pass": "both"}, {"to": "bre", "pass": "both"}, {"to": "bug", "pass": "army"}, {"to": "eng", "pass": "fleet"}, {"to": "par", "pass": "army"}],
        "pie": [{"to": "gol", "pass": "fleet"}, {"to": "mar", "pass": "both"}, {"to": "mil", "pass": "army"}, {"to": "rom", "pass": "both"}, {"to": "swi", "pass": "army"}],
        "por": [{"to": "mid", "pass": "fleet"}, {"to": "spa", "pass": "army"}, {"to": "spa/nc", "pass": "fleet"}, {"to": "spa/sc", "pass": "fleet"}],
        "pru": [{"to": "bal", "pass": "fleet"}, {"to": "ber", "pass": "both"}, {"to": "lia", "pass": "both"}, {"to": "sil", "pass": "army"}, {"to": "war", "pass": "army"}],
        "psg": [{"to": "ara/nc", "pass": "fleet"}, {"to": "ars", "pass": "fleet"}, {"to": "bag", "pass": "fleet"}, {"to": "oma", "pass": "fleet"}, {"to": "per", "pass": "fleet"}],
        "qin": [{"to": "heb", "pass": "army"}, {"to": "inn", "pass": "army"}, {"to": "pek", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "wuh", "pass": "army"}, {"to": "xin", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "red": [{"to": "ade", "pass": "fleet"}, {"to": "ara/sc", "pass": "fleet"}, {"to": "egy", "pass": "fleet"}, {"to": "eth", "pass": "fleet"}, {"to": "goa", "pass": "fleet"}, {"to": "lev/sc", "pass": "fleet"}, {"to": "mec", "pass": "fleet"}, {"to": "sud", "pass": "fleet"}],
        "rom": [{"to": "apu", "pass": "army"}, {"to": "gol", "pass": "fleet"}, {"to": "mil", "pass": "army"}, {"to": "nap", "pass": "both"}, {"to": "pie", "pass": "both"}, {"to": "tyh", "pass": "fleet"}, {"to": "ven", "pass": "army"}],
        "rum": [{"to": "bla", "pass": "fleet"}, {"to": "bud", "pass": "army"}, {"to": "bul", "pass": "both"}, {"to": "gal", "pass": "army"}, {"to": "ser", "pass": "army"}, {"to": "sev", "pass": "both"}, {"to": "ukr", "pass": "army"}],
        "sah": [{"to": "alg", "pass": "army"}, {"to": "cen", "pass": "army"}, {"to": "fez", "pass": "army"}, {"to": "mal", "pass": "army"}, {"to": "mor", "pass": "army"}, {"to": "trp", "pass": "army"}, {"to": "tun", "pass": "army"}],
        "sai": [{"to": "ann", "pass": "both"}, {"to": "cam", "pass": "both"}, {"to": "guh", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "sak": [{"to": "kar", "pass": "both"}, {"to": "soj", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}],
        "sao": [{"to": "bxc", "pass": "fleet"}, {"to": "mal", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "mor", "pass": "fleet"}],
        "sap": [{"to": "npo", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}],
        "sar": [{"to": "adr", "pass": "fleet"}, {"to": "alb", "pass": "both"}, {"to": "bud", "pass": "army"}, {"to": "ser", "pass": "army"}, {"to": "tes", "pass": "both"}],
        "sax": [{"to": "ber", "pass": "army"}, {"to": "boh", "pass": "army"}, {"to": "col", "pass": "army"}, {"to": "kie", "pass": "army"}, {"to": "mun", "pass": "army"}, {"to": "sil", "pass": "army"}],
        "scs": [{"to": "ann", "pass": "fleet"}, {"to": "bor", "pass": "fleet"}, {"to": "cel", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "for", "pass": "fleet"}, {"to": "goo", "pass": "fleet"}, {"to": "gua", "pass": "fleet"}, {"to": "guh", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "sai", "pass": "fleet"}, {"to": "sha", "pass": "fleet"}],
        "ser": [{"to": "alb", "pass": "army"}, {"to": "bud", "pass": "army"}, {"to": "bul", "pass": "army"}, {"to": "mac", "pass": "army"}, {"to": "rum", "pass": "army"}, {"to": "sar", "pass": "army"}],
        "sev": [{"to": "arm", "pass": "both"}, {"to": "bla", "pass": "fleet"}, {"to": "cau", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "rum", "pass": "both"}, {"to": "ukr", "pass": "army"}],
        "sha": [{"to": "ecs", "pass": "fleet"}, {"to": "gua", "pass": "both"}, {"to": "heb", "pass": "army"}, {"to": "heb/sc", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "wuh", "pass": "army"}],
        "shi": [{"to": "kyo", "pass": "army"}, {"to": "osa", "pass": "both"}, {"to": "spo", "pass": "fleet"}, {"to": "tok", "pass": "both"}],
        "sib": [{"to": "kam", "pass": "army"}, {"to": "man", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "oms", "pass": "army"}, {"to": "tur", "pass": "army"}, {"to": "vla", "pass": "army"}, {"to": "xin", "pass": "army"}],
        "sid": [{"to": "afg", "pass": "army"}, {"to": "ars", "pass": "fleet"}, {"to": "bom", "pass": "both"}, {"to": "del", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "per", "pass": "both"}],
        "sig": [{"to": "and", "pass": "fleet"}, {"to": "guh", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}, {"to": "tha", "pass": "army"}, {"to": "tha/ec", "pass": "fleet"}, {"to": "tha/wc", "pass": "fleet"}],
        "sil": [{"to": "ber", "pass": "army"}, {"to": "boh", "pass": "army"}, {"to": "gal", "pass": "army"}, {"to": "pru", "pass": "army"}, {"to": "sax", "pass": "army"}, {"to": "war", "pass": "army"}],
        "ska": [{"to": "den", "pass": "fleet"}, {"to": "nay", "pass": "fleet"}, {"to": "not", "pass": "fleet"}, {"to": "swe", "pass": "fleet"}],
        "soj": [{"to": "aki", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "kag", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "kor", "pass": "fleet"}, {"to": "kyo", "pass": "fleet"}, {"to": "npo", "pass": "fleet"}, {"to": "sak", "pass": "fleet"}, {"to": "sap", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}, {"to": "vla", "pass": "fleet"}],
        "soo": [{"to": "kam", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "npo", "pass": "fleet"}, {"to": "sak", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "vla", "pass": "fleet"}],
        "spa": [{"to": "gas", "pass": "army"}, {"to": "mar", "pass": "army"}, {"to": "por", "pass": "army"}],
        "spa/nc": [{"to": "gas", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "por", "pass": "fleet"}],
        "spa/sc": [{"to": "gol", "pass": "fleet"}, {"to": "mar", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "por", "pass": "fleet"}, {"to": "wms", "pass": "fleet"}],
        "spo": [{"to": "bxe", "pass": "fleet"}, {"to": "cel", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "npo", "pass": "fleet"}, {"to": "osa", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "shi", "pass": "fleet"}, {"to": "tim", "pass": "fleet"}, {"to": "tok", "pass": "fleet"}],
        "stp": [{"to": "fin", "pass": "army"}, {"to": "lia", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "nay", "pass": "army"}, {"to": "oms", "pass": "army"}],
        "stp/nc": [{"to": "bar", "pass": "fleet"}, {"to": "nay", "pass": "fleet"}],
        "stp/sc": [{"to": "fin", "pass": "fleet"}, {"to": "gob", "pass": "fleet"}, {"to": "lia", "pass": "fleet"}],
        "sud": [{"to": "cen", "pass": "army"}, {"to": "egy", "pass": "both"}, {"to": "eth", "pass": "both"}, {"to": "fez", "pass": "army"}, {"to": "ken", "pass": "army"}, {"to": "red", "pass": "fleet"}],
        "sum": [{"to": "and", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "jvs", "pass": "fleet"}],
        "swa": [{"to": "bug", "pass": "army"}, {"to": "col", "pass": "army"}, {"to": "mun", "pass": "army"}, {"to": "swi", "pass": "army"}],
        "swe": [{"to": "bal", "pass": "fleet"}, {"to": "den", "pass": "both"}, {"to": "fin", "pass": "both"}, {"to": "gob", "pass": "fleet"}, {"to": "nay", "pass": "both"}, {"to": "ska", "pass": "fleet"}],
        "swi": [{"to": "bug", "pass": "army"}, {"to": "mar", "pass": "army"}, {"to": "mil", "pass": "army"}, {"to": "mun", "pass": "army"}, {"to": "pie", "pass": "army"}, {"to": "swa", "pass": "army"}, {"to": "tyo", "pass": "army"}],
        "tes": [{"to": "adr", "pass": "fleet"}, {"to": "bud", "pass": "army"}, {"to": "sar", "pass": "both"}, {"to": "tyo", "pass": "army"}, {"to": "ven", "pass": "both"}, {"to": "vnn", "pass": "army"}],
        "tha": [{"to": "bum", "pass": "army"}, {"to": "cam", "pass": "army"}, {"to": "lao", "pass": "army"}, {"to": "sig", "pass": "army"}],
        "tha/ec": [{"to": "cam", "pass": "fleet"}, {"to": "guh", "pass": "fleet"}, {"to": "sig", "pass": "fleet"}],
        "tha/wc": [{"to": "and", "pass": "fleet"}, {"to": "bum", "pass": "fleet"}, {"to": "sig", "pass": "fleet"}],
        "tib": [{"to": "afg", "pass": "army"}, {"to": "bum", "pass": "army"}, {"to": "cal", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "nep", "pass": "army"}, {"to": "qin", "pass": "army"}, {"to": "tur", "pass": "army"}, {"to": "xin", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "tim": [{"to": "bxf", "pass": "fleet"}, {"to": "cel", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "spo", "pass": "fleet"}],
        "tok": [{"to": "aki", "pass": "both"}, {"to": "kyo", "pass": "army"}, {"to": "npo", "pass": "fleet"}, {"to": "shi", "pass": "both"}, {"to": "spo", "pass": "fleet"}],
        "trp": [{"to": "cyr", "pass": "both"}, {"to": "fez", "pass": "army"}, {"to": "ion", "pass": "fleet"}, {"to": "sah", "pass": "army"}, {"to": "tun", "pass": "both"}],
        "tsi": [{"to": "ecs", "pass": "fleet"}, {"to": "heb", "pass": "army"}, {"to": "heb/nc", "pass": "fleet"}, {"to": "heb/sc", "pass": "fleet"}, {"to": "yel", "pass": "fleet"}],
        "tun": [{"to": "alg", "pass": "both"}, {"to": "ion", "pass": "fleet"}, {"to": "sah", "pass": "army"}, {"to": "trp", "pass": "both"}, {"to": "tyh", "pass": "fleet"}],
        "tur": [{"to": "afg", "pass": "army"}, {"to": "oms", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "xin", "pass": "army"}],
        "tyh": [{"to": "alg", "pass": "fleet"}, {"to": "gol", "pass": "fleet"}, {"to": "ion", "pass": "fleet"}, {"to": "nap", "pass": "fleet"}, {"to": "rom", "pass": "fleet"}, {"to": "tun", "pass": "fleet"}, {"to": "wms", "pass": "fleet"}],
        "tyo": [{"to": "boh", "pass": "army"}, {"to": "mil", "pass": "army"}, {"to": "mun", "pass": "army"}, {"to": "swi", "pass": "army"}, {"to": "tes", "pass": "army"}, {"to": "ven", "pass": "army"}, {"to": "vnn", "pass": "army"}],
        "ukr": [{"to": "gal", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "rum", "pass": "army"}, {"to": "sev", "pass": "army"}, {"to": "war", "pass": "army"}],
        "ven": [{"to": "adr", "pass": "fleet"}, {"to": "apu", "pass": "both"}, {"to": "mil", "pass": "army"}, {"to": "rom", "pass": "army"}, {"to": "tes", "pass": "both"}, {"to": "tyo", "pass": "army"}],
        "vit": [{"to": "ann", "pass": "both"}, {"to": "goo", "pass": "fleet"}, {"to": "gua", "pass": "both"}, {"to": "lao", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "vla": [{"to": "kam", "pass": "both"}, {"to": "kor", "pass": "both"}, {"to": "man", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "soj", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}],
        "vnn": [{"to": "boh", "pass": "army"}, {"to": "bud", "pass": "army"}, {"to": "gal", "pass": "army"}, {"to": "tes", "pass": "army"}, {"to": "tyo", "pass": "army"}],
        "wal": [{"to": "eng", "pass": "fleet"}, {"to": "iri", "pass": "fleet"}, {"to": "lie", "pass": "both"}, {"to": "lon", "pass": "both"}, {"to": "yor", "pass": "army"}],
        "war": [{"to": "gal", "pass": "army"}, {"to": "lia", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "pru", "pass": "army"}, {"to": "sil", "pass": "army"}, {"to": "ukr", "pass": "army"}],
        "wio": [{"to": "ars", "pass": "fleet"}, {"to": "bom", "pass": "fleet"}, {"to": "bxg", "pass": "fleet"}, {"to": "cey", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "goa", "pass": "fleet"}, {"to": "hor", "pass": "fleet"}, {"to": "mad", "pass": "fleet"}],
        "wms": [{"to": "alg", "pass": "fleet"}, {"to": "gol", "pass": "fleet"}, {"to": "mid", "pass": "fleet"}, {"to": "mor", "pass": "fleet"}, {"to": "spa/sc", "pass": "fleet"}, {"to": "tyh", "pass": "fleet"}],
        "wuh": [{"to": "gua", "pass": "army"}, {"to": "heb", "pass": "army"}, {"to": "qin", "pass": "army"}, {"to": "sha", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "xin": [{"to": "inn", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "qin", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "yel": [{"to": "ecs", "pass": "fleet"}, {"to": "heb/nc", "pass": "fleet"}, {"to": "kor", "pass": "fleet"}, {"to": "man", "pass": "fleet"}, {"to": "pek", "pass": "fleet"}, {"to": "tsi", "pass": "fleet"}],
        "yem": [{"to": "ade", "pass": "both"}, {"to": "ara", "pass": "army"}, {"to": "ars", "pass": "fleet"}, {"to": "goa", "pass": "fleet"}, {"to": "oma", "pass": "both"}],
        "yor": [{"to": "edi", "pass": "both"}, {"to": "lie", "pass": "army"}, {"to": "lon", "pass": "both"}, {"to": "not", "pass": "fleet"}, {"to": "wal", "pass": "army"}],
        "yun": [{"to": "bum", "pass": "army"}, {"to": "gua", "pass": "army"}, {"to": "lao", "pass": "army"}, {"to": "qin", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "vit", "pass": "army"}, {"to": "wuh", "pass": "army"}],
    },
    "vietnam-war": {
        "ang": [{"to": "bur", "pass": "army"}, {"to": "kul", "pass": "army"}, {"to": "pat", "pass": "army"}, {"to": "ton", "pass": "army"}],
        "att": [{"to": "cev", "pass": "army"}, {"to": "eas", "pass": "army"}, {"to": "hue", "pass": "army"}, {"to": "pak", "pass": "army"}, {"to": "phh", "pass": "army"}, {"to": "ple", "pass": "army"}, {"to": "vin", "pass": "army"}, {"to": "vir", "pass": "army"}],
        "ban": [{"to": "bur", "pass": "army"}, {"to": "loe", "pass": "army"}, {"to": "noa", "pass": "fleet"}, {"to": "pat", "pass": "both"}, {"to": "phr", "pass": "army"}, {"to": "syk", "pass": "both"}],
        "bur": [{"to": "ang", "pass": "army"}, {"to": "ban", "pass": "army"}, {"to": "kul", "pass": "army"}, {"to": "loe", "pass": "army"}, {"to": "pat", "pass": "army"}, {"to": "ubo", "pass": "army"}],
        "cam": [{"to": "med", "pass": "fleet"}, {"to": "soa", "pass": "fleet"}, {"to": "xuy", "pass": "army"}, {"to": "xuy/ec", "pass": "fleet"}, {"to": "xuy/wc", "pass": "fleet"}],
        "cev": [{"to": "att", "pass": "army"}, {"to": "eas", "pass": "army"}, {"to": "pha", "pass": "army"}, {"to": "ple", "pass": "army"}],
        "cgo": [{"to": "kha", "pass": "fleet"}, {"to": "meo/wc", "pass": "fleet"}, {"to": "noa", "pass": "fleet"}, {"to": "pre", "pass": "fleet"}, {"to": "soa", "pass": "fleet"}, {"to": "stc", "pass": "fleet"}, {"to": "ton", "pass": "fleet"}, {"to": "xuy/wc", "pass": "fleet"}],
        "chi": [{"to": "nan", "pass": "army"}, {"to": "phr", "pass": "army"}, {"to": "syk", "pass": "army"}],
        "coa": [{"to": "eas", "pass": "fleet"}, {"to": "hai", "pass": "fleet"}, {"to": "hue", "pass": "fleet"}, {"to": "med", "pass": "fleet"}, {"to": "pac", "pass": "fleet"}, {"to": "pha", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "son", "pass": "fleet"}],
        "eas": [{"to": "att", "pass": "army"}, {"to": "cev", "pass": "army"}, {"to": "coa", "pass": "fleet"}, {"to": "hue", "pass": "both"}, {"to": "pha", "pass": "both"}],
        "hai": [{"to": "coa", "pass": "fleet"}, {"to": "non", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "son", "pass": "fleet"}],
        "han": [{"to": "nol", "pass": "army"}, {"to": "non", "pass": "fleet"}, {"to": "thh", "pass": "both"}, {"to": "thn", "pass": "both"}],
        "hue": [{"to": "att", "pass": "army"}, {"to": "coa", "pass": "fleet"}, {"to": "eas", "pass": "both"}, {"to": "son", "pass": "fleet"}, {"to": "vin", "pass": "both"}],
        "kha": [{"to": "cgo", "pass": "fleet"}, {"to": "noa", "pass": "fleet"}, {"to": "soa", "pass": "fleet"}, {"to": "syk", "pass": "both"}],
        "kul": [{"to": "ang", "pass": "army"}, {"to": "bur", "pass": "army"}, {"to": "meo", "pass": "army"}, {"to": "pak", "pass": "army"}, {"to": "ton", "pass": "army"}, {"to": "ubo", "pass": "army"}],
        "loe": [{"to": "ban", "pass": "army"}, {"to": "bur", "pass": "army"}, {"to": "phr", "pass": "army"}, {"to": "ubo", "pass": "army"}, {"to": "udo", "pass": "army"}],
        "lua": [{"to": "nah", "pass": "army"}, {"to": "nol", "pass": "army"}, {"to": "phs", "pass": "army"}, {"to": "vie", "pass": "army"}],
        "med": [{"to": "cam", "pass": "fleet"}, {"to": "coa", "pass": "fleet"}, {"to": "pac", "pass": "fleet"}, {"to": "pha", "pass": "fleet"}, {"to": "sag", "pass": "fleet"}, {"to": "soa", "pass": "fleet"}, {"to": "xuy/ec", "pass": "fleet"}],
        "meo": [{"to": "kul", "pass": "army"}, {"to": "pak", "pass": "army"}, {"to": "phn", "pass": "army"}, {"to": "pre", "pass": "army"}, {"to": "tay", "pass": "army"}, {"to": "ton", "pass": "army"}, {"to": "vir", "pass": "army"}, {"to": "xuy", "pass": "army"}],
        "meo/river": [{"to": "pak", "pass": "fleet"}, {"to": "xuy/ec", "pass": "fleet"}],
        "meo/wc": [{"to": "cgo", "pass": "fleet"}, {"to": "pre", "pass": "fleet"}, {"to": "xuy/wc", "pass": "fleet"}],
        "nah": [{"to": "lua", "pass": "army"}, {"to": "nan", "pass": "army"}],
        "nak": [{"to": "phh", "pass": "army"}, {"to": "ubo", "pass": "army"}, {"to": "udo", "pass": "army"}],
        "nan": [{"to": "chi", "pass": "army"}, {"to": "nah", "pass": "army"}, {"to": "phr", "pass": "army"}],
        "nkd": [{"to": "phh", "pass": "army"}, {"to": "udo", "pass": "army"}, {"to": "vie", "pass": "army"}, {"to": "vin", "pass": "army"}],
        "noa": [{"to": "ban", "pass": "fleet"}, {"to": "cgo", "pass": "fleet"}, {"to": "kha", "pass": "fleet"}, {"to": "pat", "pass": "fleet"}, {"to": "stc", "pass": "fleet"}, {"to": "syk", "pass": "fleet"}],
        "nol": [{"to": "han", "pass": "army"}, {"to": "lua", "pass": "army"}, {"to": "nov", "pass": "army"}, {"to": "phs", "pass": "army"}, {"to": "thh", "pass": "army"}, {"to": "thn", "pass": "army"}],
        "non": [{"to": "hai", "pass": "fleet"}, {"to": "han", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "son", "pass": "fleet"}, {"to": "thh", "pass": "fleet"}, {"to": "thn", "pass": "fleet"}],
        "nov": [{"to": "nol", "pass": "army"}, {"to": "thn", "pass": "army"}],
        "pac": [{"to": "coa", "pass": "fleet"}, {"to": "med", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "soa", "pass": "fleet"}],
        "pak": [{"to": "att", "pass": "army"}, {"to": "kul", "pass": "army"}, {"to": "meo", "pass": "army"}, {"to": "meo/river", "pass": "fleet"}, {"to": "phh", "pass": "army"}, {"to": "ubo", "pass": "both"}, {"to": "vir", "pass": "army"}],
        "pat": [{"to": "ang", "pass": "army"}, {"to": "ban", "pass": "both"}, {"to": "bur", "pass": "army"}, {"to": "noa", "pass": "fleet"}, {"to": "stc", "pass": "fleet"}, {"to": "ton", "pass": "both"}],
        "pha": [{"to": "cev", "pass": "army"}, {"to": "coa", "pass": "fleet"}, {"to": "eas", "pass": "both"}, {"to": "med", "pass": "fleet"}, {"to": "ple", "pass": "army"}, {"to": "sag", "pass": "both"}, {"to": "tay", "pass": "army"}],
        "phh": [{"to": "att", "pass": "army"}, {"to": "nak", "pass": "army"}, {"to": "nkd", "pass": "army"}, {"to": "pak", "pass": "army"}, {"to": "ubo", "pass": "army"}, {"to": "udo", "pass": "army"}, {"to": "vin", "pass": "army"}],
        "phn": [{"to": "meo", "pass": "army"}, {"to": "ple", "pass": "army"}, {"to": "tay", "pass": "army"}, {"to": "vir", "pass": "army"}],
        "phr": [{"to": "ban", "pass": "army"}, {"to": "chi", "pass": "army"}, {"to": "loe", "pass": "army"}, {"to": "nan", "pass": "army"}, {"to": "syk", "pass": "army"}],
        "phs": [{"to": "lua", "pass": "army"}, {"to": "nol", "pass": "army"}, {"to": "thh", "pass": "army"}, {"to": "vie", "pass": "army"}],
        "ple": [{"to": "att", "pass": "army"}, {"to": "cev", "pass": "army"}, {"to": "pha", "pass": "army"}, {"to": "phn", "pass": "army"}, {"to": "tay", "pass": "army"}, {"to": "vir", "pass": "army"}],
        "pre": [{"to": "cgo", "pass": "fleet"}, {"to": "meo", "pass": "army"}, {"to": "meo/wc", "pass": "fleet"}, {"to": "ton", "pass": "both"}],
        "sag": [{"to": "med", "pass": "fleet"}, {"to": "pha", "pass": "both"}, {"to": "tay", "pass": "army"}, {"to": "xuy", "pass": "army"}, {"to": "xuy/ec", "pass": "fleet"}],
        "scs": [{"to": "coa", "pass": "fleet"}, {"to": "hai", "pass": "fleet"}, {"to": "non", "pass": "fleet"}, {"to": "pac", "pass": "fleet"}],
        "soa": [{"to": "cam", "pass": "fleet"}, {"to": "cgo", "pass": "fleet"}, {"to": "kha", "pass": "fleet"}, {"to": "med", "pass": "fleet"}, {"to": "pac", "pass": "fleet"}, {"to": "xuy/wc", "pass": "fleet"}],
        "son": [{"to": "coa", "pass": "fleet"}, {"to": "hai", "pass": "fleet"}, {"to": "hue", "pass": "fleet"}, {"to": "non", "pass": "fleet"}, {"to": "thh", "pass": "fleet"}, {"to": "vin", "pass": "fleet"}],
        "stc": [{"to": "cgo", "pass": "fleet"}, {"to": "noa", "pass": "fleet"}, {"to": "pat", "pass": "fleet"}, {"to": "ton", "pass": "fleet"}],
        "syk": [{"to": "ban", "pass": "both"}, {"to": "chi", "pass": "army"}, {"to": "kha", "pass": "both"}, {"to": "noa", "pass": "fleet"}, {"to": "phr", "pass": "army"}],
        "tay": [{"to": "meo", "pass": "army"}, {"to": "pha", "pass": "army"}, {"to": "phn", "pass": "army"}, {"to": "ple", "pass": "army"}, {"to": "sag", "pass": "army"}, {"to": "xuy", "pass": "army"}],
        "thh": [{"to": "han", "pass": "both"}, {"to": "nol", "pass": "army"}, {"to": "non", "pass": "fleet"}, {"to": "phs", "pass": "army"}, {"to": "son", "pass": "fleet"}, {"to": "vin", "pass": "both"}],
        "thn": [{"to": "han", "pass": "both"}, {"to": "nol", "pass": "army"}, {"to": "non", "pass": "fleet"}, {"to": "nov", "pass": "army"}],
        "ton": [{"to": "ang", "pass": "army"}, {"to": "cgo", "pass": "fleet"}, {"to": "kul", "pass": "army"}, {"to": "meo", "pass": "army"}, {"to": "pat", "pass": "both"}, {"to": "pre", "pass": "both"}, {"to": "stc", "pass": "fleet"}],
        "ubo": [{"to": "bur", "pass": "army"}, {"to": "kul", "pass": "army"}, {"to": "loe", "pass": "army"}, {"to": "nak", "pass": "army"}, {"to": "pak", "pass": "both"}, {"to": "phh", "pass": "army"}, {"to": "udo", "pass": "army"}],
        "udo": [{"to": "loe", "pass": "army"}, {"to": "nak", "pass": "army"}, {"to": "nkd", "pass": "army"}, {"to": "phh", "pass": "army"}, {"to": "ubo", "pass": "army"}, {"to": "vie", "pass": "army"}],
        "vie": [{"to": "lua", "pass": "army"}, {"to": "nkd", "pass": "army"}, {"to": "phs", "pass": "army"}, {"to": "udo", "pass": "army"}],
        "vin": [{"to": "att", "pass": "army"}, {"to": "hue", "pass": "both"}, {"to": "nkd", "pass": "army"}, {"to": "phh", "pass": "army"}, {"to": "son", "pass": "fleet"}, {"to": "thh", "pass": "both"}],
        "vir": [{"to": "att", "pass": "army"}, {"to": "meo", "pass": "army"}, {"to": "pak", "pass": "army"}, {"to": "phn", "pass": "army"}, {"to": "ple", "pass": "army"}],
        "xuy": [{"to": "cam", "pass": "army"}, {"to": "meo", "pass": "army"}, {"to": "sag", "pass": "army"}, {"to": "tay", "pass": "army"}],
        "xuy/ec": [{"to": "cam", "pass": "fleet"}, {"to": "med", "pass": "fleet"}, {"to": "meo/river", "pass": "fleet"}, {"to": "sag", "pass": "fleet"}],
        "xuy/wc": [{"to": "cam", "pass": "fleet"}, {"to": "cgo", "pass": "fleet"}, {"to": "meo/wc", "pass": "fleet"}, {"to": "soa", "pass": "fleet"}],
    },
    "canton": {
        "afg": [{"to": "bal", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sin", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "aki": [{"to": "kyo", "pass": "both"}, {"to": "shi", "pass": "army"}, {"to": "soj", "pass": "fleet"}, {"to": "tok", "pass": "army"}, {"to": "yes", "pass": "both"}],
        "amu": [{"to": "irk", "pass": "army"}, {"to": "kha", "pass": "army"}, {"to": "man", "pass": "army"}, {"to": "mar", "pass": "army"}, {"to": "mon", "pass": "army"}],
        "ara": [{"to": "ase", "pass": "fleet"}, {"to": "bag", "pass": "both"}, {"to": "dam", "pass": "army"}, {"to": "dam/sc", "pass": "fleet"}, {"to": "pgu", "pass": "fleet"}, {"to": "red", "pass": "fleet"}],
        "arm": [{"to": "bla", "pass": "fleet"}, {"to": "con", "pass": "both"}, {"to": "kaz", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sev", "pass": "both"}],
        "ase": [{"to": "ara", "pass": "fleet"}, {"to": "bal", "pass": "fleet"}, {"to": "bom", "pass": "fleet"}, {"to": "pgu", "pass": "fleet"}, {"to": "red", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "asm": [{"to": "bur", "pass": "army"}, {"to": "cal", "pass": "army"}, {"to": "chu", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "bag": [{"to": "ara", "pass": "both"}, {"to": "con", "pass": "army"}, {"to": "dam", "pass": "army"}, {"to": "per", "pass": "both"}, {"to": "pgu", "pass": "fleet"}],
        "bal": [{"to": "afg", "pass": "army"}, {"to": "ase", "pass": "fleet"}, {"to": "bom", "pass": "both"}, {"to": "del", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "per", "pass": "both"}, {"to": "pgu", "pass": "fleet"}],
        "ban": [{"to": "cel", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "sio", "pass": "fleet"}],
        "bla": [{"to": "arm", "pass": "fleet"}, {"to": "bul/ec", "pass": "fleet"}, {"to": "con", "pass": "fleet"}, {"to": "rum", "pass": "fleet"}, {"to": "sev", "pass": "fleet"}],
        "bob": [{"to": "bur", "pass": "fleet"}, {"to": "cal", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "gom", "pass": "fleet"}, {"to": "mad", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "bom": [{"to": "ase", "pass": "fleet"}, {"to": "bal", "pass": "both"}, {"to": "del", "pass": "army"}, {"to": "mad", "pass": "both"}, {"to": "wio", "pass": "fleet"}],
        "bor": [{"to": "cel", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "sar", "pass": "both"}],
        "bul": [{"to": "con", "pass": "army"}, {"to": "rum", "pass": "army"}],
        "bul/ec": [{"to": "bla", "pass": "fleet"}, {"to": "con", "pass": "fleet"}, {"to": "rum", "pass": "fleet"}],
        "bul/sc": [{"to": "con", "pass": "fleet"}, {"to": "med", "pass": "fleet"}],
        "bur": [{"to": "asm", "pass": "army"}, {"to": "bob", "pass": "fleet"}, {"to": "cal", "pass": "both"}, {"to": "gom", "pass": "fleet"}, {"to": "lao", "pass": "army"}, {"to": "sia", "pass": "army"}, {"to": "sia/wc", "pass": "fleet"}, {"to": "yun", "pass": "army"}],
        "cal": [{"to": "asm", "pass": "army"}, {"to": "bob", "pass": "fleet"}, {"to": "bur", "pass": "both"}, {"to": "del", "pass": "army"}, {"to": "mad", "pass": "both"}],
        "cam": [{"to": "gos", "pass": "fleet"}, {"to": "hue", "pass": "army"}, {"to": "lao", "pass": "army"}, {"to": "sai", "pass": "both"}, {"to": "sia", "pass": "army"}, {"to": "sia/ec", "pass": "fleet"}],
        "can": [{"to": "chu", "pass": "army"}, {"to": "han", "pass": "army"}, {"to": "hko", "pass": "army"}, {"to": "sha", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "can/ec": [{"to": "ecs", "pass": "fleet"}, {"to": "hko", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "sha", "pass": "fleet"}],
        "can/sc": [{"to": "han", "pass": "fleet"}, {"to": "hko", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "cel": [{"to": "ban", "pass": "fleet"}, {"to": "bor", "pass": "fleet"}, {"to": "cpo", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "sar", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "chu": [{"to": "asm", "pass": "army"}, {"to": "can", "pass": "army"}, {"to": "kan", "pass": "army"}, {"to": "pek", "pass": "army"}, {"to": "sha", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "con": [{"to": "arm", "pass": "both"}, {"to": "bag", "pass": "army"}, {"to": "bla", "pass": "fleet"}, {"to": "bul", "pass": "army"}, {"to": "bul/ec", "pass": "fleet"}, {"to": "bul/sc", "pass": "fleet"}, {"to": "dam", "pass": "army"}, {"to": "dam/wc", "pass": "fleet"}, {"to": "med", "pass": "fleet"}, {"to": "per", "pass": "army"}],
        "cpo": [{"to": "cel", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "pse", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}, {"to": "tok", "pass": "fleet"}, {"to": "yes", "pass": "fleet"}],
        "dam": [{"to": "ara", "pass": "army"}, {"to": "bag", "pass": "army"}, {"to": "con", "pass": "army"}, {"to": "egy", "pass": "army"}],
        "dam/sc": [{"to": "ara", "pass": "fleet"}, {"to": "egy", "pass": "fleet"}, {"to": "red", "pass": "fleet"}],
        "dam/wc": [{"to": "con", "pass": "fleet"}, {"to": "egy", "pass": "fleet"}, {"to": "med", "pass": "fleet"}],
        "del": [{"to": "bal", "pass": "army"}, {"to": "bom", "pass": "army"}, {"to": "cal", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "mad", "pass": "army"}],
        "ecs": [{"to": "can/ec", "pass": "fleet"}, {"to": "for", "pass": "fleet"}, {"to": "kor", "pass": "fleet"}, {"to": "pse", "pass": "fleet"}, {"to": "sas", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "sha", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "yel", "pass": "fleet"}],
        "egy": [{"to": "dam", "pass": "army"}, {"to": "dam/sc", "pass": "fleet"}, {"to": "dam/wc", "pass": "fleet"}, {"to": "med", "pass": "fleet"}, {"to": "red", "pass": "fleet"}],
        "eio": [{"to": "bob", "pass": "fleet"}, {"to": "gom", "pass": "fleet"}, {"to": "sio", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "for": [{"to": "ecs", "pass": "fleet"}, {"to": "pse", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "gom": [{"to": "bob", "pass": "fleet"}, {"to": "bur", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "mal", "pass": "fleet"}, {"to": "sia/wc", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}],
        "gos": [{"to": "cam", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "mal", "pass": "fleet"}, {"to": "sai", "pass": "fleet"}, {"to": "sia/ec", "pass": "fleet"}],
        "han": [{"to": "can", "pass": "army"}, {"to": "can/sc", "pass": "fleet"}, {"to": "hue", "pass": "both"}, {"to": "lao", "pass": "army"}, {"to": "scs", "pass": "fleet"}, {"to": "yun", "pass": "army"}],
        "hko": [{"to": "can", "pass": "army"}, {"to": "can/ec", "pass": "fleet"}, {"to": "can/sc", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "hue": [{"to": "cam", "pass": "army"}, {"to": "han", "pass": "both"}, {"to": "kar", "pass": "fleet"}, {"to": "lao", "pass": "army"}, {"to": "sai", "pass": "both"}, {"to": "scs", "pass": "fleet"}],
        "irk": [{"to": "amu", "pass": "army"}, {"to": "kha", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "tom", "pass": "army"}],
        "jav": [{"to": "ban", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "sio", "pass": "fleet"}],
        "jse": [{"to": "ban", "pass": "fleet"}, {"to": "bor", "pass": "fleet"}, {"to": "cel", "pass": "fleet"}, {"to": "gom", "pass": "fleet"}, {"to": "gos", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "mal", "pass": "fleet"}, {"to": "sio", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}],
        "kan": [{"to": "chu", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "pek", "pass": "army"}, {"to": "sin", "pass": "army"}, {"to": "tib", "pass": "army"}],
        "kar": [{"to": "bor", "pass": "fleet"}, {"to": "gos", "pass": "fleet"}, {"to": "hue", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "sai", "pass": "fleet"}, {"to": "sar", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "kas": [{"to": "afg", "pass": "army"}, {"to": "bal", "pass": "army"}, {"to": "del", "pass": "army"}, {"to": "sin", "pass": "army"}, {"to": "tib", "pass": "army"}],
        "kaz": [{"to": "arm", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "sev", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "tom", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "kha": [{"to": "amu", "pass": "army"}, {"to": "irk", "pass": "army"}, {"to": "mar", "pass": "both"}, {"to": "soj", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}],
        "kor": [{"to": "ecs", "pass": "fleet"}, {"to": "man", "pass": "both"}, {"to": "mar", "pass": "both"}, {"to": "soj", "pass": "fleet"}, {"to": "yel", "pass": "fleet"}],
        "kyo": [{"to": "aki", "pass": "both"}, {"to": "sas", "pass": "both"}, {"to": "shi", "pass": "army"}, {"to": "soj", "pass": "fleet"}],
        "lao": [{"to": "bur", "pass": "army"}, {"to": "cam", "pass": "army"}, {"to": "han", "pass": "army"}, {"to": "hue", "pass": "army"}, {"to": "sia", "pass": "army"}, {"to": "yun", "pass": "army"}],
        "mad": [{"to": "bob", "pass": "fleet"}, {"to": "bom", "pass": "both"}, {"to": "cal", "pass": "both"}, {"to": "del", "pass": "army"}, {"to": "wio", "pass": "fleet"}],
        "mal": [{"to": "gom", "pass": "fleet"}, {"to": "gos", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "sia", "pass": "army"}, {"to": "sia/ec", "pass": "fleet"}, {"to": "sia/wc", "pass": "fleet"}],
        "man": [{"to": "amu", "pass": "army"}, {"to": "kor", "pass": "both"}, {"to": "mar", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "pek", "pass": "both"}, {"to": "yel", "pass": "fleet"}],
        "mar": [{"to": "amu", "pass": "army"}, {"to": "kha", "pass": "both"}, {"to": "kor", "pass": "both"}, {"to": "man", "pass": "army"}, {"to": "soj", "pass": "fleet"}],
        "med": [{"to": "bul/sc", "pass": "fleet"}, {"to": "con", "pass": "fleet"}, {"to": "dam/wc", "pass": "fleet"}, {"to": "egy", "pass": "fleet"}],
        "mon": [{"to": "amu", "pass": "army"}, {"to": "irk", "pass": "army"}, {"to": "kan", "pass": "army"}, {"to": "man", "pass": "army"}, {"to": "pek", "pass": "army"}, {"to": "sin", "pass": "army"}, {"to": "tom", "pass": "army"}],
        "mos": [{"to": "kaz", "pass": "army"}, {"to": "sev", "pass": "army"}, {"to": "sib", "pass": "army"}],
        "pek": [{"to": "chu", "pass": "army"}, {"to": "kan", "pass": "army"}, {"to": "man", "pass": "both"}, {"to": "mon", "pass": "army"}, {"to": "sha", "pass": "both"}, {"to": "yel", "pass": "fleet"}],
        "per": [{"to": "afg", "pass": "army"}, {"to": "arm", "pass": "army"}, {"to": "bag", "pass": "both"}, {"to": "bal", "pass": "both"}, {"to": "con", "pass": "army"}, {"to": "pgu", "pass": "fleet"}, {"to": "tur", "pass": "army"}],
        "pgu": [{"to": "ara", "pass": "fleet"}, {"to": "ase", "pass": "fleet"}, {"to": "bag", "pass": "fleet"}, {"to": "bal", "pass": "fleet"}, {"to": "per", "pass": "fleet"}],
        "phi": [{"to": "cel", "pass": "fleet"}, {"to": "cpo", "pass": "fleet"}, {"to": "pse", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "pse": [{"to": "cpo", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "for", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "sas", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}, {"to": "shi", "pass": "fleet"}, {"to": "tok", "pass": "fleet"}],
        "red": [{"to": "ara", "pass": "fleet"}, {"to": "ase", "pass": "fleet"}, {"to": "dam/sc", "pass": "fleet"}, {"to": "egy", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "rum": [{"to": "bla", "pass": "fleet"}, {"to": "bul", "pass": "army"}, {"to": "bul/ec", "pass": "fleet"}, {"to": "sev", "pass": "both"}],
        "sai": [{"to": "cam", "pass": "both"}, {"to": "gos", "pass": "fleet"}, {"to": "hue", "pass": "both"}, {"to": "kar", "pass": "fleet"}],
        "sar": [{"to": "bor", "pass": "both"}, {"to": "cel", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "scs", "pass": "fleet"}],
        "sas": [{"to": "ecs", "pass": "fleet"}, {"to": "kyo", "pass": "both"}, {"to": "pse", "pass": "fleet"}, {"to": "shi", "pass": "both"}, {"to": "soj", "pass": "fleet"}],
        "scs": [{"to": "can/ec", "pass": "fleet"}, {"to": "can/sc", "pass": "fleet"}, {"to": "cel", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "for", "pass": "fleet"}, {"to": "han", "pass": "fleet"}, {"to": "hko", "pass": "fleet"}, {"to": "hue", "pass": "fleet"}, {"to": "kar", "pass": "fleet"}, {"to": "phi", "pass": "fleet"}, {"to": "pse", "pass": "fleet"}, {"to": "sar", "pass": "fleet"}],
        "sev": [{"to": "arm", "pass": "both"}, {"to": "bla", "pass": "fleet"}, {"to": "kaz", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "rum", "pass": "both"}],
        "sha": [{"to": "can", "pass": "army"}, {"to": "can/ec", "pass": "fleet"}, {"to": "chu", "pass": "army"}, {"to": "ecs", "pass": "fleet"}, {"to": "pek", "pass": "both"}, {"to": "yel", "pass": "fleet"}],
        "shi": [{"to": "aki", "pass": "army"}, {"to": "kyo", "pass": "army"}, {"to": "pse", "pass": "fleet"}, {"to": "sas", "pass": "both"}, {"to": "tok", "pass": "both"}],
        "sia": [{"to": "bur", "pass": "army"}, {"to": "cam", "pass": "army"}, {"to": "lao", "pass": "army"}, {"to": "mal", "pass": "army"}],
        "sia/ec": [{"to": "cam", "pass": "fleet"}, {"to": "gos", "pass": "fleet"}, {"to": "mal", "pass": "fleet"}],
        "sia/wc": [{"to": "bur", "pass": "fleet"}, {"to": "gom", "pass": "fleet"}, {"to": "mal", "pass": "fleet"}],
        "sib": [{"to": "irk", "pass": "army"}, {"to": "kaz", "pass": "army"}, {"to": "mos", "pass": "army"}, {"to": "tom", "pass": "army"}],
        "sin": [{"to": "afg", "pass": "army"}, {"to": "kan", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "tib", "pass": "army"}, {"to": "tom", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "sio": [{"to": "ban", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "jav", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "sum", "pass": "fleet"}, {"to": "wio", "pass": "fleet"}],
        "soj": [{"to": "aki", "pass": "fleet"}, {"to": "ecs", "pass": "fleet"}, {"to": "kha", "pass": "fleet"}, {"to": "kor", "pass": "fleet"}, {"to": "kyo", "pass": "fleet"}, {"to": "mar", "pass": "fleet"}, {"to": "sas", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}, {"to": "yes", "pass": "fleet"}],
        "soo": [{"to": "cpo", "pass": "fleet"}, {"to": "kha", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "yes", "pass": "fleet"}],
        "sum": [{"to": "eio", "pass": "fleet"}, {"to": "gom", "pass": "fleet"}, {"to": "jse", "pass": "fleet"}, {"to": "sio", "pass": "fleet"}],
        "tib": [{"to": "asm", "pass": "army"}, {"to": "chu", "pass": "army"}, {"to": "kan", "pass": "army"}, {"to": "kas", "pass": "army"}, {"to": "sin", "pass": "army"}],
        "tok": [{"to": "aki", "pass": "army"}, {"to": "cpo", "pass": "fleet"}, {"to": "pse", "pass": "fleet"}, {"to": "shi", "pass": "both"}, {"to": "yes", "pass": "both"}],
        "tom": [{"to": "irk", "pass": "army"}, {"to": "kaz", "pass": "army"}, {"to": "mon", "pass": "army"}, {"to": "sib", "pass": "army"}, {"to": "sin", "pass": "army"}, {"to": "tur", "pass": "army"}],
        "tur": [{"to": "afg", "pass": "army"}, {"to": "kaz", "pass": "army"}, {"to": "per", "pass": "army"}, {"to": "sin", "pass": "army"}, {"to": "tom", "pass": "army"}],
        "wio": [{"to": "ase", "pass": "fleet"}, {"to": "bob", "pass": "fleet"}, {"to": "bom", "pass": "fleet"}, {"to": "eio", "pass": "fleet"}, {"to": "mad", "pass": "fleet"}, {"to": "red", "pass": "fleet"}, {"to": "sio", "pass": "fleet"}],
        "yel": [{"to": "ecs", "pass": "fleet"}, {"to": "kor", "pass": "fleet"}, {"to": "man", "pass": "fleet"}, {"to": "pek", "pass": "fleet"}, {"to": "sha", "pass": "fleet"}],
        "yes": [{"to": "aki", "pass": "both"}, {"to": "cpo", "pass": "fleet"}, {"to": "soj", "pass": "fleet"}, {"to": "soo", "pass": "fleet"}, {"to": "tok", "pass": "both"}],
        "yun": [{"to": "asm", "pass": "army"}, {"to": "bur", "pass": "army"}, {"to": "can", "pass": "army"}, {"to": "chu", "pass": "army"}, {"to": "han", "pass": "army"}, {"to": "lao", "pass": "army"}],
    },
}


def _check_symmetry(variant_id, adjacency_map):
    edges = set()
    for source, adjacencies in adjacency_map.items():
        for adjacency in adjacencies:
            edges.add((source, adjacency["to"], adjacency["pass"]))
    for source, target, pass_ in sorted(edges):
        if (target, source, pass_) not in edges:
            raise ValueError(
                f"{variant_id}: adjacency {source} -> {target} ({pass_}) "
                f"is not mirrored on the other side"
            )


def backfill_adjacencies(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")
    for variant_id, adjacency_map in ADJACENCIES.items():
        _check_symmetry(variant_id, adjacency_map)
        variant = Variant.objects.get(id=variant_id)
        for province_id, adjacencies in adjacency_map.items():
            province = Province.objects.get(variant=variant, province_id=province_id)
            province.adjacencies = adjacencies
            province.save(update_fields=["adjacencies"])


def clear_adjacencies(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")
    for variant_id in ADJACENCIES:
        variant = Variant.objects.get(id=variant_id)
        Province.objects.filter(variant=variant).update(adjacencies=[])


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0015_backfill_adjacencies_classical_ivg_hundred"),
    ]

    operations = [
        migrations.RunPython(backfill_adjacencies, clear_adjacencies),
    ]
