# Generated by Django 6.0.6 on 2026-07-06 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game_id", models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ("notification_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("no_device", "No device"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="notificatio_user_id_c4d245_idx"),
                    models.Index(fields=["notification_type"], name="notificatio_notific_a5f01d_idx"),
                ],
            },
        ),
    ]
