# Generated by Django 6.1 on 2026-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdelivery",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed"), ("expired", "Expired")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
