# Generated by Django 6.1.1 on 2026-09-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_add_expired_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdelivery",
            name="channel",
            field=models.CharField(choices=[("push", "Push")], max_length=20),
        ),
    ]
