# Generated by Django 6.1.1 on 2026-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_alter_notificationdelivery_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdelivery",
            name="tag",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
