import type {
  GameList,
  Variant,
  PhaseRetrieve,
  Member,
  Nation,
  Province,
  Unit,
  SupplyCenter,
  StatusEnum,
  UserProfile,
} from "@/api/generated/endpoints";

export const mockNations: Nation[] = [
  { name: "Austria", color: "#FF0000" },
  { name: "England", color: "#0000FF" },
  { name: "France", color: "#00FFFF" },
  { name: "Germany", color: "#000000" },
  { name: "Italy", color: "#00FF00" },
  { name: "Russia", color: "#FFFFFF" },
  { name: "Turkey", color: "#FFFF00" },
];

export const mockMembers: Member[] = [
  {
    id: 1,
    name: "Alice",
    picture: null,
    nation: "Austria",
    isCurrentUser: false,
  },
  {
    id: 2,
    name: "Bob",
    picture: null,
    nation: "England",
    isCurrentUser: false,
  },
  {
    id: 3,
    name: "Charlie",
    picture: null,
    nation: "France",
    isCurrentUser: false,
  },
  {
    id: 4,
    name: "Diana",
    picture: null,
    nation: "Germany",
    isCurrentUser: false,
  },
  {
    id: 5,
    name: "Eve",
    picture: null,
    nation: "Italy",
    isCurrentUser: false,
  },
  {
    id: 6,
    name: "Frank",
    picture: null,
    nation: "Russia",
    isCurrentUser: false,
  },
  {
    id: 7,
    name: "You",
    picture: null,
    nation: "Turkey",
    isCurrentUser: true,
  },
];

export const mockProvinces: Province[] = [
  {
    id: "vie",
    name: "Vienna",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
  {
    id: "lon",
    name: "London",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
  {
    id: "par",
    name: "Paris",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
  {
    id: "ber",
    name: "Berlin",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
  {
    id: "rom",
    name: "Rome",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
  {
    id: "mos",
    name: "Moscow",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
  {
    id: "con",
    name: "Constantinople",
    type: "land",
    supplyCenter: true,
    parentId: null,
    namedCoastIds: [],
  },
];

export const mockPhaseMovement: PhaseRetrieve = {
  id: 1,
  ordinal: 1,
  season: "Spring",
  year: 1901,
  name: "Spring 1901 Movement",
  type: "Movement",
  remainingTime: 86400,
  scheduledResolution: "2024-01-15T12:00:00Z",
  status: "active" as StatusEnum,
  units: [
    {
      type: "Army",
      nation: mockNations[0],
      province: mockProvinces[0],
      dislodged: false,
      dislodgedBy: null,
    },
    {
      type: "Fleet",
      nation: mockNations[1],
      province: mockProvinces[1],
      dislodged: false,
      dislodgedBy: null,
    },
    {
      type: "Army",
      nation: mockNations[2],
      province: mockProvinces[2],
      dislodged: false,
      dislodgedBy: null,
    },
    {
      type: "Army",
      nation: mockNations[3],
      province: mockProvinces[3],
      dislodged: false,
      dislodgedBy: null,
    },
    {
      type: "Fleet",
      nation: mockNations[4],
      province: mockProvinces[4],
      dislodged: false,
      dislodgedBy: null,
    },
    {
      type: "Army",
      nation: mockNations[5],
      province: mockProvinces[5],
      dislodged: false,
      dislodgedBy: null,
    },
    {
      type: "Fleet",
      nation: mockNations[6],
      province: mockProvinces[6],
      dislodged: false,
      dislodgedBy: null,
    },
  ],
  supplyCenters: mockProvinces.map((province, index) => ({
    province,
    nation: mockNations[index],
  })),
};

export const mockPhaseRetreat: PhaseRetrieve = {
  id: 2,
  ordinal: 2,
  season: "Spring",
  year: 1901,
  name: "Spring 1901 Retreat",
  type: "Retreat",
  remainingTime: 43200,
  scheduledResolution: "2024-01-16T00:00:00Z",
  status: "active" as StatusEnum,
  units: [
    {
      type: "Army",
      nation: mockNations[0],
      province: mockProvinces[0],
      dislodged: true,
      dislodgedBy: null,
    },
  ],
  supplyCenters: mockProvinces.map((province, index) => ({
    province,
    nation: mockNations[index],
  })),
};

export const mockPhaseAdjustment: PhaseRetrieve = {
  id: 3,
  ordinal: 3,
  season: "Fall",
  year: 1901,
  name: "Fall 1901 Adjustment",
  type: "Adjustment",
  remainingTime: 172800,
  scheduledResolution: "2024-01-18T12:00:00Z",
  status: "active" as StatusEnum,
  units: mockPhaseMovement.units,
  supplyCenters: mockProvinces.map((province, index) => ({
    province,
    nation: mockNations[index % mockNations.length],
  })),
};

export const mockGames: GameList[] = [
  {
    id: "game-1",
    name: "European Diplomacy Championship",
    status: "active",
    canJoin: false,
    canLeave: true,
    variantId: "Classical",
    phases: [1, 2, 3, 4, 5],
    private: false,
    movementPhaseDuration: "24 hours",
    nationAssignment: "manual",
    members: mockMembers,
    victory: null,
    sandbox: false,
  },
  {
    id: "game-2",
    name: "Quick Evening Game",
    status: "active",
    canJoin: false,
    canLeave: true,
    variantId: "Classical",
    phases: [1, 2],
    private: false,
    movementPhaseDuration: "12 hours",
    nationAssignment: "random",
    members: mockMembers,
    victory: null,
    sandbox: false,
  },
  {
    id: "game-3",
    name: "New Game - Need Players!",
    status: "pending",
    canJoin: true,
    canLeave: false,
    variantId: "Classical",
    phases: [1],
    private: false,
    movementPhaseDuration: "48 hours",
    nationAssignment: "random",
    members: mockMembers.slice(0, 2),
    victory: null,
    sandbox: false,
  },
  {
    id: "game-4",
    name: "Weekend Tournament",
    status: "pending",
    canJoin: false,
    canLeave: true,
    variantId: "Classical",
    phases: [1],
    private: true,
    movementPhaseDuration: "24 hours",
    nationAssignment: "manual",
    members: mockMembers.slice(0, 3),
    victory: null,
    sandbox: false,
  },
  {
    id: "game-5",
    name: "Historic Battle - Finished",
    status: "completed",
    canJoin: false,
    canLeave: false,
    variantId: "Classical",
    phases: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    private: false,
    movementPhaseDuration: "24 hours",
    nationAssignment: "manual",
    members: mockMembers,
    victory: {
      id: 1,
      type: "solo",
      winningPhaseId: 10,
      members: [mockMembers[0]],
    },
    sandbox: false,
  },
  {
    id: "game-6",
    name: "Three-Way Draw",
    status: "completed",
    canJoin: false,
    canLeave: false,
    variantId: "Italy vs Germany",
    phases: [1, 2, 3, 4, 5, 6, 7, 8],
    private: false,
    movementPhaseDuration: "48 hours",
    nationAssignment: "random",
    members: mockMembers,
    victory: {
      id: 2,
      type: "draw",
      winningPhaseId: 8,
      members: [mockMembers[0], mockMembers[1], mockMembers[2]],
    },
    sandbox: false,
  },
];

export const mockActiveGames = mockGames.filter((g) => g.status === "active");
export const mockPendingGames = mockGames.filter((g) => g.status === "pending");
export const mockCompletedGames = mockGames.filter(
  (g) => g.status === "completed"
);

export const mockSandboxGames: GameList[] = [
  {
    id: "sandbox-1",
    name: "Practice Game - Classical",
    status: "active",
    canJoin: false,
    canLeave: true,
    variantId: "Classical",
    phases: [1, 2, 3],
    private: false,
    movementPhaseDuration: "manual",
    nationAssignment: "random",
    members: mockMembers,
    victory: null,
    sandbox: true,
  },
  {
    id: "sandbox-2",
    name: "Testing New Strategies",
    status: "active",
    canJoin: false,
    canLeave: true,
    variantId: "Classical",
    phases: [1],
    private: false,
    movementPhaseDuration: "manual",
    nationAssignment: "random",
    members: mockMembers,
    victory: null,
    sandbox: true,
  },
];

export const mockVariants: Variant[] = [
  {
    id: "Classical",
    name: "Classical Diplomacy",
    description: "The original Diplomacy game",
    author: "Allan B. Calhamer",
    nations: mockNations,
    provinces: mockProvinces,
    templatePhase: {
      id: 1,
      ordinal: 1,
      season: "Spring",
      year: 1901,
      name: "Spring 1901 Movement",
      type: "Movement",
      remainingTime: 0,
      scheduledResolution: "1901-01-01T00:00:00Z",
      status: "template" as StatusEnum,
      units: [],
      supplyCenters: [],
    },
  },
  {
    id: "Italy vs Germany",
    name: "Italy vs Germany",
    description: "A 2-player variant",
    author: "Unknown",
    nations: [mockNations[4], mockNations[3]],
    provinces: mockProvinces.slice(3, 5),
    templatePhase: {
      id: 2,
      ordinal: 1,
      season: "Spring",
      year: 1901,
      name: "Spring 1901 Movement",
      type: "Movement",
      remainingTime: 0,
      scheduledResolution: "1901-01-01T00:00:00Z",
      status: "template" as StatusEnum,
      units: [],
      supplyCenters: [],
    },
  },
];

export const mockUserProfile: UserProfile = {
  id: 1,
  name: "John Doe",
  picture: null,
  email: "john.doe@example.com",
};
