# Generated by Django 6.0.6 on 2026-06-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_create_bot_user"),
        ("member", "0007_member_seeking_replacement_replaced_by"),
        ("phase", "0015_backfill_orders_outcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("negotiate", "Negotiate"),
                            ("commit", "Commit"),
                            ("reply", "Reply"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")], default="success", max_length=20
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                ("system", models.TextField(blank=True)),
                ("user_content", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="member.member",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="llm_calls", to="phase.phase"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
