# Generated by Django 6.0.6 on 2026-07-02 01:30

from django.db import migrations, models

BOT_USER_USERNAME = "diplicitybot"


def mark_default_bot(apps, schema_editor):
    BotProfile = apps.get_model("bot", "BotProfile")
    BotProfile.objects.filter(user__username=BOT_USER_USERNAME).update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_llmcall"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_default_bot, migrations.RunPython.noop),
    ]
