# Generated by Django 6.0.6 on 2026-07-02 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_seed_bot_roster"),
        ("channel", "0004_channelmessage_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcall",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_calls",
                to="channel.channel",
            ),
        ),
    ]
