# Generated by Django 4.2.24 on 2025-09-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variant', '0007_remove_provinces_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nation_set', to='variant.variant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'variant')},
            },
        ),
    ]
