# Generated by Django 4.2.24 on 2025-09-24 13:15

from django.db import migrations


def populate_nations(apps, schema_editor):
    """Populate Nation model with data from Variant.nations_data."""
    Variant = apps.get_model('variant', 'Variant')
    Nation = apps.get_model('nation', 'Nation')

    for variant in Variant.objects.all():
        if variant.nations_data:
            for nation_data in variant.nations_data:
                Nation.objects.get_or_create(
                    name=nation_data['name'],
                    variant=variant,
                    defaults={
                        'color': nation_data['color'],
                    }
                )


def reverse_populate_nations(apps, schema_editor):
    """Remove all Nation records."""
    Nation = apps.get_model('nation', 'Nation')
    Nation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nation', '0001_initial'),
        ('variant', '0007_remove_provinces_data'),
    ]

    operations = [
        migrations.RunPython(
            populate_nations,
            reverse_populate_nations,
        ),
    ]
