# Generated by Django 4.2.24 on 2025-09-24 14:34

from django.db import migrations


def add_italy_vs_germany_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    # Get the Italy vs Germany variant
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")

    # Italy vs Germany nations data
    nations_data = [
        {"name": "Germany", "color": "#90A4AE"},
        {"name": "Italy", "color": "#4CAF50"},
    ]

    for nation_data in nations_data:
        Nation.objects.create(name=nation_data["name"], color=nation_data["color"], variant=italy_germany_variant)


def remove_italy_vs_germany_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    Nation.objects.filter(variant=italy_germany_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nation", "0002_add_classical_nations"),
        ("variant", "0003_add_italy_vs_germany_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_nations,
            remove_italy_vs_germany_nations,
        ),
    ]