# Generated by generate_variant_migrations.py on 2025-10-24 22:24:01

from django.db import migrations


def add_hundred_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    hundred_variant = Variant.objects.get(id="hundred")

    nations_data = [{'name': 'England', 'color': '#2196F3'}, {'name': 'Burgundy', 'color': '#808080'}, {'name': 'France', 'color': '#80DEEA'}]

    for nation_data in nations_data:
        Nation.objects.create(
            name=nation_data["name"],
            color=nation_data["color"],
            variant=hundred_variant
        )


def remove_hundred_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    hundred_variant = Variant.objects.get(id="hundred")
    Nation.objects.filter(variant=hundred_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nation", "0003_add_italy_vs_germany_nations"),
        ("variant", "0004_add_hundred_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_hundred_nations,
            remove_hundred_nations,
        ),
    ]
