# Generated by generate_variant_migrations.py on 2026-05-07 00:00:00

from django.db import migrations


def add_vietnam_war_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")

    nations_data = [{'name': 'North Vietnam', 'color': '#FD0000'}, {'name': 'Thailand', 'color': '#006FFF'}, {'name': 'South Vietnam', 'color': '#F0D211'}, {'name': 'Cambodia', 'color': '#708D9E'}, {'name': 'Laos', 'color': '#03853A'}]

    for nation_data in nations_data:
        Nation.objects.create(
            name=nation_data["name"],
            color=nation_data["color"],
            variant=vietnam_war_variant
        )


def remove_vietnam_war_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")
    Nation.objects.filter(variant=vietnam_war_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nation", "0005_add_youngstown_redux_nations"),
        ("variant", "0007_add_vietnam_war_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_vietnam_war_nations,
            remove_vietnam_war_nations,
        ),
    ]
