# Generated by generate_variant_migrations.py on 2026-05-11 19:04:23

from django.db import migrations


def add_canton_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    canton_variant = Variant.objects.get(id="canton")

    nations_data = [{'name': 'Turkey', 'color': '#FFC107'}, {'name': 'Britain', 'color': '#2198F5'}, {'name': 'China', 'color': '#F33F35'}, {'name': 'Holland', 'color': '#F56B26'}, {'name': 'Japan', 'color': '#4CAF50'}, {'name': 'Russia', 'color': '#F5F5F5'}, {'name': 'France', 'color': '#80DEEA'}]

    for nation_data in nations_data:
        Nation.objects.create(
            name=nation_data["name"],
            color=nation_data["color"],
            variant=canton_variant
        )


def remove_canton_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    canton_variant = Variant.objects.get(id="canton")
    Nation.objects.filter(variant=canton_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nation", "0006_add_vietnam_war_nations"),
        ("variant", "0008_add_canton_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_canton_nations,
            remove_canton_nations,
        ),
    ]
