# Generated by Django 4.2.29 on 2026-03-28 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmember',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
