# Generated by Django 6.0.6 on 2026-07-01 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0003_backfill_public_channel_members"),
        ("phase", "0015_backfill_orders_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmessage",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_messages",
                to="phase.phase",
            ),
        ),
    ]
