# Generated by Django 6.1 on 2026-08-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0006_widen_channel_name"),
        ("member", "0007_member_seeking_replacement_replaced_by"),
        ("phase", "0019_unique_live_phase_ordinal_per_game"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="channelmessage",
            index=models.Index(fields=["channel", "created_at"], name="channel_cha_channel_8ab307_idx"),
        ),
    ]
