# Generated by Django 6.1.1 on 2026-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0006_widen_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="title",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
