# Generated by Django 6.1.1 on 2026-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0007_channel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelevent",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
