# Generated by Django 4.2.24 on 2025-09-24 13:56

from django.db import migrations


def add_classical_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    # Get the classical variant
    classical_variant = Variant.objects.get(id="classical")

    # Classical nations data
    nations_data = [
        {"name": "England", "color": "#2196F3"},
        {"name": "France", "color": "#80DEEA"},
        {"name": "Germany", "color": "#90A4AE"},
        {"name": "Italy", "color": "#4CAF50"},
        {"name": "Austria", "color": "#F44336"},
        {"name": "Turkey", "color": "#FFC107"},
        {"name": "Russia", "color": "#F5F5F5"},
    ]

    for nation_data in nations_data:
        Nation.objects.create(name=nation_data["name"], color=nation_data["color"], variant=classical_variant)


def remove_classical_nations(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")

    classical_variant = Variant.objects.get(id="classical")
    Nation.objects.filter(variant=classical_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nation", "0001_initial"),
        ("variant", "0002_add_classical_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_nations,
            remove_classical_nations,
        ),
    ]
