# Generated by Django 4.2.27 on 2026-02-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_is_game_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nmr_extensions_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
