# Generated by Django 6.0.6 on 2026-06-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_civil_disorder'),
        ('game', '0017_backfill_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_game_master_per_game',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_game_master',
        ),
    ]
