# Generated by Django 6.0.6 on 2026-06-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0006_remove_member_unique_game_master_per_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaces",
                to="member.member",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="seeking_replacement",
            field=models.BooleanField(default=False),
        ),
    ]
