# Generated by Django 6.1 on 2026-08-23 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_remove_game_nation_assignment"),
        ("member", "0007_member_seeking_replacement_replaced_by"),
        ("nation", "0014_add_non_playable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("replaced_by__isnull", True)),
                fields=("game", "nation"),
                name="member_unique_nation_per_game",
            ),
        ),
        migrations.AddField(
            model_name="nationpreference",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="nation_preferences", to="member.member"
            ),
        ),
        migrations.AddField(
            model_name="nationpreference",
            name="nation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="member_preferences", to="nation.nation"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nationpreference",
            unique_together={("member", "nation"), ("member", "rank")},
        ),
    ]
