# Generated by Django 6.1 on 2026-08-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0007_member_seeking_replacement_replaced_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="mustered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
