# Generated by Django 6.1 on 2026-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0008_member_mustered_at"),
        ("member", "0008_nationpreference_and_more"),
    ]

    operations = []
