# Generated by Django 6.1 on 2026-08-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0011_unique_member_per_user_per_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="mustered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
