# Generated by Django 6.1.1 on 2026-09-06 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0025_game_muster_deadline_game_muster_job_id_and_more"),
        ("member", "0012_member_mustered_at"),
        ("nation", "0014_add_non_playable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="kind",
            field=models.CharField(
                choices=[("player", "Player"), ("game_master", "Game Master")], default="player", max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "game_master")), fields=("game",), name="member_unique_game_master_per_game"
            ),
        ),
    ]
