# Generated by Django 4.2.24 on 2025-09-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('province', '0001_initial'),
        ('nation', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Army', 'Army'), ('Fleet', 'Fleet')], max_length=10)),
                ('dislodged_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislodges', to='unit.unit')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='nation.nation')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='game.phase')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='province.province')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
