# Generated by Django 4.2.24 on 2025-09-24 14:23

from django.db import migrations


def add_classical_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("game", "Phase")
    Unit = apps.get_model("unit", "Unit")

    # Get the classical variant and template phase
    classical_variant = Variant.objects.get(id="classical")
    template_phase = Phase.objects.get(game=None, variant=classical_variant, status="template")

    # Classical units data
    units_data = [
        {"type": "Fleet", "nation": "England", "province": "edi"},
        {"type": "Army", "nation": "England", "province": "lvp"},
        {"type": "Fleet", "nation": "England", "province": "lon"},
        {"type": "Fleet", "nation": "France", "province": "bre"},
        {"type": "Army", "nation": "France", "province": "par"},
        {"type": "Army", "nation": "France", "province": "mar"},
        {"type": "Fleet", "nation": "Germany", "province": "kie"},
        {"type": "Army", "nation": "Germany", "province": "ber"},
        {"type": "Army", "nation": "Germany", "province": "mun"},
        {"type": "Army", "nation": "Italy", "province": "ven"},
        {"type": "Army", "nation": "Italy", "province": "rom"},
        {"type": "Fleet", "nation": "Italy", "province": "nap"},
        {"type": "Fleet", "nation": "Austria", "province": "tri"},
        {"type": "Army", "nation": "Austria", "province": "vie"},
        {"type": "Army", "nation": "Austria", "province": "bud"},
        {"type": "Fleet", "nation": "Russia", "province": "stp/sc"},
        {"type": "Army", "nation": "Russia", "province": "mos"},
        {"type": "Army", "nation": "Russia", "province": "war"},
        {"type": "Fleet", "nation": "Russia", "province": "sev"},
        {"type": "Army", "nation": "Turkey", "province": "con"},
        {"type": "Army", "nation": "Turkey", "province": "smy"},
        {"type": "Fleet", "nation": "Turkey", "province": "ank"},
    ]

    # Create units
    for unit_data in units_data:
        # Get the nation and province objects
        nation = Nation.objects.get(name=unit_data["nation"], variant=classical_variant)
        province = Province.objects.get(province_id=unit_data["province"], variant=classical_variant)

        Unit.objects.create(
            phase=template_phase,
            type=unit_data["type"],
            nation=nation,
            province=province,
            dislodged_by=None,
        )


def remove_classical_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("game", "Phase")
    Unit = apps.get_model("unit", "Unit")

    classical_variant = Variant.objects.get(id="classical")
    template_phase = Phase.objects.get(game=None, variant=classical_variant, status="template")
    Unit.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0001_initial"),
        ("variant", "0002_add_classical_variant"),
        ("nation", "0002_add_classical_nations"),
        ("province", "0002_add_classical_provinces"),
        ("game", "0002_add_classical_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_units,
            remove_classical_units,
        ),
    ]
