# Generated by Django 4.2.24 on 2025-09-24 14:35

from django.db import migrations


def add_italy_vs_germany_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("game", "Phase")
    Unit = apps.get_model("unit", "Unit")

    # Get the Italy vs Germany variant and template phase
    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    template_phase = Phase.objects.get(game=None, variant=italy_germany_variant, status="template")

    # Italy vs Germany units data
    units_data = [
        {"type": "Fleet", "nation": "Germany", "province": "kie"},
        {"type": "Army", "nation": "Germany", "province": "ber"},
        {"type": "Army", "nation": "Germany", "province": "mun"},
        {"type": "Army", "nation": "Italy", "province": "ven"},
        {"type": "Army", "nation": "Italy", "province": "rom"},
        {"type": "Fleet", "nation": "Italy", "province": "nap"},
    ]

    # Create units
    for unit_data in units_data:
        # Get the nation and province objects
        nation = Nation.objects.get(name=unit_data["nation"], variant=italy_germany_variant)
        province = Province.objects.get(province_id=unit_data["province"], variant=italy_germany_variant)

        Unit.objects.create(
            phase=template_phase,
            type=unit_data["type"],
            nation=nation,
            province=province,
            dislodged_by=None,
        )


def remove_italy_vs_germany_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("game", "Phase")
    Unit = apps.get_model("unit", "Unit")

    italy_germany_variant = Variant.objects.get(id="italy-vs-germany")
    template_phase = Phase.objects.get(game=None, variant=italy_germany_variant, status="template")
    Unit.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0002_add_classical_units"),
        ("variant", "0003_add_italy_vs_germany_variant"),
        ("nation", "0003_add_italy_vs_germany_nations"),
        ("province", "0003_add_italy_vs_germany_provinces"),
        ("game", "0003_add_italy_vs_germany_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_italy_vs_germany_units,
            remove_italy_vs_germany_units,
        ),
    ]
