# Generated by generate_variant_migrations.py on 2025-10-24 22:24:01

from django.db import migrations


def add_hundred_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    Unit = apps.get_model("unit", "Unit")

    hundred_variant = Variant.objects.get(id="hundred")
    template_phase = Phase.objects.get(game=None, variant=hundred_variant, status="template")

    units_data = [{'type': 'Army', 'nation': 'Burgundy', 'province': 'dij'}, {'type': 'Army', 'nation': 'France', 'province': 'pro'}, {'type': 'Fleet', 'nation': 'England', 'province': 'lon'}, {'type': 'Army', 'nation': 'France', 'province': 'orl'}, {'type': 'Army', 'nation': 'France', 'province': 'par'}, {'type': 'Fleet', 'nation': 'England', 'province': 'dev'}, {'type': 'Fleet', 'nation': 'Burgundy', 'province': 'hol'}, {'type': 'Army', 'nation': 'France', 'province': 'dau'}, {'type': 'Army', 'nation': 'Burgundy', 'province': 'lux'}, {'type': 'Army', 'nation': 'France', 'province': 'tou'}, {'type': 'Army', 'nation': 'England', 'province': 'cal'}, {'type': 'Army', 'nation': 'England', 'province': 'nom'}, {'type': 'Army', 'nation': 'England', 'province': 'guy'}, {'type': 'Army', 'nation': 'Burgundy', 'province': 'fla'}]

    for unit_data in units_data:
        nation = Nation.objects.get(variant=hundred_variant, name=unit_data["nation"])
        province = Province.objects.get(variant=hundred_variant, province_id=unit_data["province"])

        Unit.objects.create(
            nation=nation,
            province=province,
            phase=template_phase,
            type=unit_data["type"]
        )


def remove_hundred_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    Unit = apps.get_model("unit", "Unit")

    hundred_variant = Variant.objects.get(id="hundred")
    template_phase = Phase.objects.get(game=None, variant=hundred_variant, status="template")
    Unit.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0003_add_italy_vs_germany_units"),
        ("variant", "0004_add_hundred_variant"),
        ("nation", "0004_add_hundred_nations"),
        ("province", "0010_add_hundred_provinces"),
        ("phase", "0005_add_hundred_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_hundred_units,
            remove_hundred_units,
        ),
    ]
