# Generated by Django 4.2.26 on 2025-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0004_add_hundred_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='dislodged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dislodged', False), ('dislodged_by__isnull', True)), ('dislodged', True), _connector='OR'), name='dislodged_by_requires_dislodged'),
        ),
    ]
