# Generated by Django 4.2.26 on 2025-11-26 14:50

from django.db import migrations


def populate_dislodged_field(apps, schema_editor):
    Unit = apps.get_model('unit', 'Unit')
    Unit.objects.filter(dislodged_by__isnull=False).update(dislodged=True)


def reverse_populate_dislodged_field(apps, schema_editor):
    Unit = apps.get_model('unit', 'Unit')
    Unit.objects.all().update(dislodged=False)


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0005_unit_dislodged_unit_dislodged_by_requires_dislodged'),
    ]

    operations = [
        migrations.RunPython(populate_dislodged_field, reverse_populate_dislodged_field),
    ]
