# Generated by generate_variant_migrations.py on 2026-05-07 00:00:00

from django.db import migrations


def add_vietnam_war_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    Unit = apps.get_model("unit", "Unit")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")
    template_phase = Phase.objects.get(game=None, variant=vietnam_war_variant, status="template")

    units_data = [{'type': 'Army', 'nation': 'North Vietnam', 'province': 'thh'}, {'type': 'Fleet', 'nation': 'Thailand', 'province': 'pat'}, {'type': 'Army', 'nation': 'Thailand', 'province': 'ban'}, {'type': 'Fleet', 'nation': 'South Vietnam', 'province': 'eas'}, {'type': 'Army', 'nation': 'Cambodia', 'province': 'ang'}, {'type': 'Fleet', 'nation': 'South Vietnam', 'province': 'cam'}, {'type': 'Fleet', 'nation': 'Cambodia', 'province': 'pre'}, {'type': 'Army', 'nation': 'Laos', 'province': 'nah'}, {'type': 'Army', 'nation': 'Laos', 'province': 'pak'}, {'type': 'Army', 'nation': 'Laos', 'province': 'vie'}, {'type': 'Army', 'nation': 'North Vietnam', 'province': 'thn'}, {'type': 'Army', 'nation': 'Thailand', 'province': 'loe'}, {'type': 'Army', 'nation': 'South Vietnam', 'province': 'sag'}, {'type': 'Fleet', 'nation': 'North Vietnam', 'province': 'han'}, {'type': 'Army', 'nation': 'Cambodia', 'province': 'meo'}]

    for unit_data in units_data:
        nation = Nation.objects.get(variant=vietnam_war_variant, name=unit_data["nation"])
        province = Province.objects.get(variant=vietnam_war_variant, province_id=unit_data["province"])

        Unit.objects.create(
            nation=nation,
            province=province,
            phase=template_phase,
            type=unit_data["type"]
        )


def remove_vietnam_war_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    Unit = apps.get_model("unit", "Unit")

    vietnam_war_variant = Variant.objects.get(id="vietnam-war")
    template_phase = Phase.objects.get(game=None, variant=vietnam_war_variant, status="template")
    Unit.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0007_add_youngstown_redux_units"),
        ("variant", "0007_add_vietnam_war_variant"),
        ("nation", "0006_add_vietnam_war_nations"),
        ("province", "0012_add_vietnam_war_provinces"),
        ("phase", "0011_add_vietnam_war_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_vietnam_war_units,
            remove_vietnam_war_units,
        ),
    ]
