# Generated by generate_variant_migrations.py on 2026-05-11 19:04:23

from django.db import migrations


def add_canton_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Nation = apps.get_model("nation", "Nation")
    Province = apps.get_model("province", "Province")
    Phase = apps.get_model("phase", "Phase")
    Unit = apps.get_model("unit", "Unit")

    canton_variant = Variant.objects.get(id="canton")
    template_phase = Phase.objects.get(game=None, variant=canton_variant, status="template")

    units_data = [{'type': 'Army', 'nation': 'Britain', 'province': 'cal'}, {'type': 'Fleet', 'nation': 'Holland', 'province': 'sum'}, {'type': 'Fleet', 'nation': 'Turkey', 'province': 'con'}, {'type': 'Fleet', 'nation': 'China', 'province': 'pek'}, {'type': 'Army', 'nation': 'Japan', 'province': 'kyo'}, {'type': 'Fleet', 'nation': 'Holland', 'province': 'jav'}, {'type': 'Army', 'nation': 'China', 'province': 'sha'}, {'type': 'Army', 'nation': 'China', 'province': 'tib'}, {'type': 'Fleet', 'nation': 'Japan', 'province': 'sas'}, {'type': 'Fleet', 'nation': 'Britain', 'province': 'mad'}, {'type': 'Army', 'nation': 'Britain', 'province': 'del'}, {'type': 'Army', 'nation': 'China', 'province': 'chu'}, {'type': 'Army', 'nation': 'France', 'province': 'han'}, {'type': 'Fleet', 'nation': 'France', 'province': 'sai'}, {'type': 'Army', 'nation': 'France', 'province': 'hue'}, {'type': 'Fleet', 'nation': 'Russia', 'province': 'kha'}, {'type': 'Fleet', 'nation': 'Holland', 'province': 'bor'}, {'type': 'Fleet', 'nation': 'Japan', 'province': 'tok'}, {'type': 'Fleet', 'nation': 'Russia', 'province': 'sev'}, {'type': 'Army', 'nation': 'Turkey', 'province': 'dam'}, {'type': 'Army', 'nation': 'Russia', 'province': 'mos'}, {'type': 'Army', 'nation': 'Russia', 'province': 'irk'}, {'type': 'Army', 'nation': 'Turkey', 'province': 'bag'}]

    for unit_data in units_data:
        nation = Nation.objects.get(variant=canton_variant, name=unit_data["nation"])
        province = Province.objects.get(variant=canton_variant, province_id=unit_data["province"])

        Unit.objects.create(
            nation=nation,
            province=province,
            phase=template_phase,
            type=unit_data["type"]
        )


def remove_canton_units(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Phase = apps.get_model("phase", "Phase")
    Unit = apps.get_model("unit", "Unit")

    canton_variant = Variant.objects.get(id="canton")
    template_phase = Phase.objects.get(game=None, variant=canton_variant, status="template")
    Unit.objects.filter(phase=template_phase).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0008_add_vietnam_war_units"),
        ("variant", "0008_add_canton_variant"),
        ("nation", "0007_add_canton_nations"),
        ("province", "0013_add_canton_provinces"),
        ("phase", "0012_add_canton_template_phase"),
    ]

    operations = [
        migrations.RunPython(
            add_canton_units,
            remove_canton_units,
        ),
    ]
