# Generated by Django 6.0.8 on 2026-08-12 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0009_add_canton_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="dislodged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dislodges",
                to="unit.unit",
            ),
        ),
    ]
