# Generated by Django 4.2.24 on 2025-09-24 13:58

from django.db import migrations


def add_classical_provinces(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    # Get the classical variant
    classical_variant = Variant.objects.get(id="classical")

    # Classical provinces data
    provinces_data = [
        {"id": "adr", "name": "Adriatic Sea", "supply_center": False, "type": "sea"},
        {"id": "aeg", "name": "Aegean Sea", "supply_center": False, "type": "sea"},
        {"id": "alb", "name": "Albania", "supply_center": False, "type": "coastal"},
        {"id": "ank", "name": "Ankara", "supply_center": True, "type": "coastal"},
        {"id": "apu", "name": "Apulia", "supply_center": False, "type": "coastal"},
        {"id": "arm", "name": "Armenia", "supply_center": False, "type": "coastal"},
        {"id": "bal", "name": "Baltic Sea", "supply_center": False, "type": "sea"},
        {"id": "bar", "name": "Barents Sea", "supply_center": False, "type": "sea"},
        {"id": "bel", "name": "Belgium", "supply_center": True, "type": "coastal"},
        {"id": "ber", "name": "Berlin", "supply_center": True, "type": "coastal"},
        {"id": "bla", "name": "Black Sea", "supply_center": False, "type": "sea"},
        {"id": "boh", "name": "Bohemia", "supply_center": False, "type": "land"},
        {"id": "bre", "name": "Brest", "supply_center": True, "type": "coastal"},
        {"id": "bud", "name": "Budapest", "supply_center": True, "type": "land"},
        {"id": "bul", "name": "Bulgaria", "supply_center": True, "type": "coastal"},
        {"id": "bul/ec", "name": "Bulgaria (EC)", "supply_center": False, "type": "sea"},
        {"id": "bul/sc", "name": "Bulgaria (SC)", "supply_center": False, "type": "sea"},
        {"id": "bur", "name": "Burgundy", "supply_center": False, "type": "land"},
        {"id": "cly", "name": "Clyde", "supply_center": False, "type": "coastal"},
        {"id": "con", "name": "Constantinople", "supply_center": True, "type": "coastal"},
        {"id": "den", "name": "Denmark", "supply_center": True, "type": "coastal"},
        {"id": "edi", "name": "Edinburgh", "supply_center": True, "type": "coastal"},
        {"id": "eng", "name": "English Channel", "supply_center": False, "type": "sea"},
        {"id": "fin", "name": "Finland", "supply_center": False, "type": "coastal"},
        {"id": "gal", "name": "Galicia", "supply_center": False, "type": "land"},
        {"id": "gas", "name": "Gascony", "supply_center": False, "type": "coastal"},
        {"id": "gol", "name": "Gulf of Lyon", "supply_center": False, "type": "sea"},
        {"id": "gre", "name": "Greece", "supply_center": True, "type": "coastal"},
        {"id": "hel", "name": "Heligoland Bight", "supply_center": False, "type": "sea"},
        {"id": "hol", "name": "Holland", "supply_center": True, "type": "coastal"},
        {"id": "ion", "name": "Ionian Sea", "supply_center": False, "type": "sea"},
        {"id": "iri", "name": "Irish Sea", "supply_center": False, "type": "sea"},
        {"id": "kie", "name": "Kiel", "supply_center": True, "type": "coastal"},
        {"id": "lon", "name": "London", "supply_center": True, "type": "coastal"},
        {"id": "lvn", "name": "Livonia", "supply_center": False, "type": "coastal"},
        {"id": "lvp", "name": "Liverpool", "supply_center": True, "type": "coastal"},
        {"id": "mar", "name": "Marseilles", "supply_center": True, "type": "coastal"},
        {"id": "mid", "name": "Mid-Atlantic", "supply_center": False, "type": "sea"},
        {"id": "mos", "name": "Moscow", "supply_center": True, "type": "land"},
        {"id": "mun", "name": "Munich", "supply_center": True, "type": "land"},
        {"id": "naf", "name": "North Africa", "supply_center": False, "type": "coastal"},
        {"id": "nat", "name": "North Atlantic", "supply_center": False, "type": "sea"},
        {"id": "nrg", "name": "Norwegian Sea", "supply_center": False, "type": "sea"},
        {"id": "nth", "name": "North Sea", "supply_center": False, "type": "sea"},
        {"id": "nwy", "name": "Norway", "supply_center": True, "type": "coastal"},
        {"id": "par", "name": "Paris", "supply_center": True, "type": "land"},
        {"id": "pic", "name": "Picardy", "supply_center": False, "type": "coastal"},
        {"id": "pie", "name": "Piedmont", "supply_center": False, "type": "coastal"},
        {"id": "por", "name": "Portugal", "supply_center": True, "type": "coastal"},
        {"id": "pru", "name": "Prussia", "supply_center": False, "type": "coastal"},
        {"id": "rom", "name": "Rome", "supply_center": True, "type": "coastal"},
        {"id": "ruh", "name": "Ruhr", "supply_center": False, "type": "land"},
        {"id": "rum", "name": "Rumania", "supply_center": True, "type": "coastal"},
        {"id": "ser", "name": "Serbia", "supply_center": True, "type": "land"},
        {"id": "sev", "name": "Sevastopol", "supply_center": True, "type": "coastal"},
        {"id": "sil", "name": "Silesia", "supply_center": False, "type": "land"},
        {"id": "ska", "name": "Skagerakk (SKA)", "supply_center": False, "type": "sea"},
        {"id": "smy", "name": "Smyrna", "supply_center": True, "type": "coastal"},
        {"id": "spa", "name": "Spain", "supply_center": True, "type": "coastal"},
        {"id": "spa/nc", "name": "Spain (NC)", "supply_center": False, "type": "sea"},
        {"id": "spa/sc", "name": "Spain (SC)", "supply_center": False, "type": "sea"},
        {"id": "stp", "name": "St. Petersburg", "supply_center": True, "type": "coastal"},
        {"id": "stp/nc", "name": "St. Petersburg (NC)", "supply_center": False, "type": "sea"},
        {"id": "stp/sc", "name": "St. Petersburg (SC)", "supply_center": False, "type": "sea"},
        {"id": "swe", "name": "Sweden", "supply_center": True, "type": "coastal"},
        {"id": "syr", "name": "Syria", "supply_center": False, "type": "coastal"},
        {"id": "tri", "name": "Trieste", "supply_center": True, "type": "coastal"},
        {"id": "tun", "name": "Tunis", "supply_center": True, "type": "coastal"},
        {"id": "tus", "name": "Tuscany", "supply_center": False, "type": "coastal"},
        {"id": "tys", "name": "Tyrrhenian Sea", "supply_center": False, "type": "sea"},
        {"id": "ukr", "name": "Ukraine", "supply_center": False, "type": "land"},
        {"id": "ven", "name": "Venice", "supply_center": True, "type": "coastal"},
        {"id": "vie", "name": "Vienna", "supply_center": True, "type": "land"},
        {"id": "wal", "name": "Wales", "supply_center": False, "type": "coastal"},
        {"id": "war", "name": "Warsaw", "supply_center": True, "type": "land"},
        {"id": "wes", "name": "West Mediterranean", "supply_center": False, "type": "sea"},
        {"id": "yor", "name": "Yorkshire", "supply_center": False, "type": "coastal"},
        {"id": "bot", "name": "Gulf of Bothnia", "supply_center": False, "type": "sea"},
        {"id": "tyr", "name": "Tyrolia", "supply_center": False, "type": "land"},
        {"id": "eas", "name": "East Med", "supply_center": False, "type": "sea"},
        {"id": "nap", "name": "Naples", "supply_center": True, "type": "coastal"},
    ]

    for province_data in provinces_data:
        Province.objects.create(
            province_id=province_data["id"],
            name=province_data["name"],
            type=province_data["type"],
            supply_center=province_data["supply_center"],
            variant=classical_variant,
        )


def remove_classical_provinces(apps, schema_editor):
    Variant = apps.get_model("variant", "Variant")
    Province = apps.get_model("province", "Province")

    classical_variant = Variant.objects.get(id="classical")
    Province.objects.filter(variant=classical_variant).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("province", "0001_initial"),
        ("variant", "0002_add_classical_variant"),
    ]

    operations = [
        migrations.RunPython(
            add_classical_provinces,
            remove_classical_provinces,
        ),
    ]
