name: Test UX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and run tests
      run: |
        docker build -t diplicity-web -f packages/web/Dockerfile packages/web
        docker run --rm diplicity-web npm run build
