name: Test Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Set up Docker Compose
      run: |
        docker compose up -d db worker
        # Wait for services to be ready
        sleep 10
        
    - name: Run service tests
      run: |
        docker compose run test-service
      env:
        POSTGRES_DB: diplicity
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        DJANGO_SUPERUSER_USERNAME: admin
        DJANGO_SUPERUSER_EMAIL: admin@example.com
