name: Test Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Create empty .env file for docker-compose
      run: touch .env

    - name: Set up Docker Compose
      run: |
        docker compose up -d db
        # Wait for services to be ready
        sleep 10
        
    - name: Run service tests
      run: |
        docker compose run --rm service python3 -m pytest
      env:
        DATABASE_NAME: diplicity
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: db
        DATABASE_PORT: 5432
